/* Generated by Yosys 0.51+85 (git sha1 d3aec12fe, clang++ 18.1.8 -fPIC -O3) */

module adder(b, o, a);
  wire \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  wire \$13 ;
  wire \$14 ;
  wire \$15 ;
  wire \$16 ;
  wire \$17 ;
  wire \$18 ;
  wire \$19 ;
  wire \$2 ;
  wire \$20 ;
  wire \$21 ;
  wire \$22 ;
  wire \$23 ;
  wire \$24 ;
  wire \$25 ;
  wire \$26 ;
  wire \$27 ;
  wire \$28 ;
  wire \$29 ;
  wire \$3 ;
  wire \$30 ;
  wire \$31 ;
  wire \$32 ;
  wire \$33 ;
  wire \$34 ;
  wire \$35 ;
  wire \$4 ;
  wire \$5 ;
  wire \$6 ;
  wire \$7 ;
  wire \$8 ;
  wire \$9 ;
  wire \$signal ;
  wire \$signal$10 ;
  wire \$signal$100 ;
  wire \$signal$101 ;
  wire \$signal$102 ;
  wire \$signal$103 ;
  wire \$signal$104 ;
  wire \$signal$11 ;
  wire \$signal$12 ;
  wire \$signal$13 ;
  wire \$signal$14 ;
  wire \$signal$15 ;
  wire \$signal$16 ;
  wire \$signal$17 ;
  wire \$signal$177 ;
  wire \$signal$18 ;
  wire \$signal$19 ;
  wire \$signal$20 ;
  wire \$signal$21 ;
  wire \$signal$22 ;
  wire \$signal$23 ;
  wire \$signal$24 ;
  wire \$signal$25 ;
  wire \$signal$26 ;
  wire \$signal$27 ;
  wire \$signal$28 ;
  wire \$signal$29 ;
  wire \$signal$30 ;
  wire \$signal$31 ;
  wire \$signal$32 ;
  wire \$signal$33 ;
  wire \$signal$34 ;
  wire \$signal$35 ;
  wire \$signal$36 ;
  wire \$signal$37 ;
  wire \$signal$38 ;
  wire \$signal$39 ;
  wire \$signal$40 ;
  wire \$signal$41 ;
  wire \$signal$42 ;
  wire \$signal$43 ;
  wire \$signal$44 ;
  wire \$signal$45 ;
  wire \$signal$46 ;
  wire \$signal$47 ;
  wire \$signal$48 ;
  wire \$signal$49 ;
  wire \$signal$50 ;
  wire \$signal$51 ;
  wire \$signal$52 ;
  wire \$signal$53 ;
  wire \$signal$54 ;
  wire \$signal$55 ;
  wire \$signal$56 ;
  wire \$signal$57 ;
  wire \$signal$58 ;
  wire \$signal$59 ;
  wire \$signal$6 ;
  wire \$signal$60 ;
  wire \$signal$61 ;
  wire \$signal$62 ;
  wire \$signal$63 ;
  wire \$signal$64 ;
  wire \$signal$65 ;
  wire \$signal$66 ;
  wire \$signal$67 ;
  wire \$signal$68 ;
  wire \$signal$69 ;
  wire \$signal$7 ;
  wire \$signal$70 ;
  wire \$signal$73 ;
  wire \$signal$74 ;
  wire \$signal$75 ;
  wire \$signal$76 ;
  wire \$signal$77 ;
  wire \$signal$78 ;
  wire \$signal$79 ;
  wire \$signal$8 ;
  wire \$signal$80 ;
  wire \$signal$81 ;
  wire \$signal$82 ;
  wire \$signal$83 ;
  wire \$signal$84 ;
  wire \$signal$85 ;
  wire \$signal$86 ;
  wire \$signal$87 ;
  wire \$signal$88 ;
  wire \$signal$89 ;
  wire \$signal$9 ;
  wire \$signal$90 ;
  wire \$signal$91 ;
  wire \$signal$92 ;
  wire \$signal$93 ;
  wire \$signal$94 ;
  wire \$signal$95 ;
  wire \$signal$96 ;
  wire \$signal$97 ;
  wire \$signal$98 ;
  wire \$signal$99 ;
  input [32:0] a;
  wire [32:0] a;
  wire [32:0] \a$3 ;
  input [32:0] b;
  wire [32:0] b;
  wire [32:0] \b$4 ;
  wire g_new;
  wire \g_new$108 ;
  wire \g_new$111 ;
  wire \g_new$112 ;
  wire \g_new$115 ;
  wire \g_new$116 ;
  wire \g_new$119 ;
  wire \g_new$120 ;
  wire \g_new$123 ;
  wire \g_new$124 ;
  wire \g_new$127 ;
  wire \g_new$128 ;
  wire \g_new$131 ;
  wire \g_new$132 ;
  wire \g_new$135 ;
  wire \g_new$136 ;
  wire \g_new$139 ;
  wire \g_new$140 ;
  wire \g_new$143 ;
  wire \g_new$144 ;
  wire \g_new$147 ;
  wire \g_new$148 ;
  wire \g_new$151 ;
  wire \g_new$152 ;
  wire \g_new$155 ;
  wire \g_new$156 ;
  wire \g_new$159 ;
  wire \g_new$160 ;
  wire \g_new$163 ;
  wire \g_new$164 ;
  wire \g_new$165 ;
  wire \g_new$166 ;
  wire \g_new$167 ;
  wire \g_new$168 ;
  wire \g_new$169 ;
  wire \g_new$170 ;
  wire \g_new$171 ;
  wire \g_new$172 ;
  wire \g_new$173 ;
  wire \g_new$174 ;
  wire \g_new$175 ;
  wire \g_new$176 ;
  wire \g_new$178 ;
  wire \g_new$179 ;
  wire \g_new$180 ;
  wire \g_new$181 ;
  wire \g_new$182 ;
  wire \g_new$183 ;
  wire \g_new$184 ;
  wire \g_new$185 ;
  wire \g_new$186 ;
  wire \g_new$187 ;
  wire \g_new$188 ;
  wire \g_new$189 ;
  wire \g_new$190 ;
  wire \g_new$191 ;
  wire \g_new$192 ;
  output [32:0] o;
  wire [32:0] o;
  wire [32:0] \o$72 ;
  wire [32:0] o2;
  wire p_new;
  wire \p_new$106 ;
  wire \p_new$109 ;
  wire \p_new$110 ;
  wire \p_new$113 ;
  wire \p_new$114 ;
  wire \p_new$117 ;
  wire \p_new$118 ;
  wire \p_new$121 ;
  wire \p_new$122 ;
  wire \p_new$125 ;
  wire \p_new$126 ;
  wire \p_new$129 ;
  wire \p_new$130 ;
  wire \p_new$133 ;
  wire \p_new$134 ;
  wire \p_new$137 ;
  wire \p_new$138 ;
  wire \p_new$141 ;
  wire \p_new$142 ;
  wire \p_new$145 ;
  wire \p_new$146 ;
  wire \p_new$149 ;
  wire \p_new$150 ;
  wire \p_new$153 ;
  wire \p_new$154 ;
  wire \p_new$157 ;
  wire \p_new$158 ;
  wire \p_new$161 ;
  wire \p_new$162 ;
  \adder.U$0  \U$0  (
    .a(a),
    .b(b),
    .\port$1$0 (\$signal$73 ),
    .\port$2$0 (\$signal )
  );
  \adder.U$1  \U$1  (
    .a(a),
    .b(b),
    .\port$3$0 (\$signal$74 ),
    .\port$4$0 (\$signal$7 )
  );
  \adder.U$10  \U$10  (
    .a(a),
    .b(b),
    .\port$21$0 (\$signal$83 ),
    .\port$22$0 (\$signal$25 )
  );
  sg13g2_a21o_1 \U$100  (
    .A1(\p_new$114 ),
    .A2(\g_new$155 ),
    .B1(\g_new$115 ),
    .X(\g_new$170 )
  );
  sg13g2_a21o_1 \U$101  (
    .A1(\p_new$118 ),
    .A2(\g_new$166 ),
    .B1(\g_new$119 ),
    .X(\g_new$171 )
  );
  sg13g2_a21o_1 \U$102  (
    .A1(\p_new$122 ),
    .A2(\g_new$163 ),
    .B1(\g_new$123 ),
    .X(\g_new$172 )
  );
  sg13g2_a21o_1 \U$103  (
    .A1(\p_new$126 ),
    .A2(\g_new$167 ),
    .B1(\g_new$127 ),
    .X(\g_new$173 )
  );
  sg13g2_a21o_1 \U$104  (
    .A1(\p_new$130 ),
    .A2(\g_new$165 ),
    .B1(\g_new$131 ),
    .X(\g_new$174 )
  );
  sg13g2_a21o_1 \U$105  (
    .A1(\p_new$134 ),
    .A2(\g_new$168 ),
    .B1(\g_new$135 ),
    .X(\g_new$175 )
  );
  sg13g2_a21o_1 \U$106  (
    .A1(\$signal$9 ),
    .A2(g_new),
    .B1(\$signal$75 ),
    .X(\g_new$178 )
  );
  sg13g2_a21o_1 \U$107  (
    .A1(\$signal$13 ),
    .A2(\g_new$139 ),
    .B1(\$signal$77 ),
    .X(\g_new$179 )
  );
  sg13g2_a21o_1 \U$108  (
    .A1(\$signal$17 ),
    .A2(\g_new$169 ),
    .B1(\$signal$79 ),
    .X(\g_new$180 )
  );
  sg13g2_a21o_1 \U$109  (
    .A1(\$signal$21 ),
    .A2(\g_new$155 ),
    .B1(\$signal$81 ),
    .X(\g_new$181 )
  );
  \adder.U$11  \U$11  (
    .a(a),
    .b(b),
    .\port$23$0 (\$signal$84 ),
    .\port$24$0 (\$signal$27 )
  );
  sg13g2_a21o_1 \U$110  (
    .A1(\$signal$25 ),
    .A2(\g_new$170 ),
    .B1(\$signal$83 ),
    .X(\g_new$182 )
  );
  sg13g2_a21o_1 \U$111  (
    .A1(\$signal$29 ),
    .A2(\g_new$166 ),
    .B1(\$signal$85 ),
    .X(\g_new$183 )
  );
  sg13g2_a21o_1 \U$112  (
    .A1(\$signal$33 ),
    .A2(\g_new$171 ),
    .B1(\$signal$87 ),
    .X(\g_new$184 )
  );
  sg13g2_a21o_1 \U$113  (
    .A1(\$signal$37 ),
    .A2(\g_new$163 ),
    .B1(\$signal$89 ),
    .X(\g_new$185 )
  );
  sg13g2_a21o_1 \U$114  (
    .A1(\$signal$41 ),
    .A2(\g_new$172 ),
    .B1(\$signal$91 ),
    .X(\g_new$186 )
  );
  sg13g2_a21o_1 \U$115  (
    .A1(\$signal$45 ),
    .A2(\g_new$167 ),
    .B1(\$signal$93 ),
    .X(\g_new$187 )
  );
  sg13g2_a21o_1 \U$116  (
    .A1(\$signal$49 ),
    .A2(\g_new$173 ),
    .B1(\$signal$95 ),
    .X(\g_new$188 )
  );
  sg13g2_a21o_1 \U$117  (
    .A1(\$signal$53 ),
    .A2(\g_new$165 ),
    .B1(\$signal$97 ),
    .X(\g_new$189 )
  );
  sg13g2_a21o_1 \U$118  (
    .A1(\$signal$57 ),
    .A2(\g_new$174 ),
    .B1(\$signal$99 ),
    .X(\g_new$190 )
  );
  sg13g2_a21o_1 \U$119  (
    .A1(\$signal$61 ),
    .A2(\g_new$168 ),
    .B1(\$signal$101 ),
    .X(\g_new$191 )
  );
  \adder.U$12  \U$12  (
    .a(a),
    .b(b),
    .\port$25$0 (\$signal$85 ),
    .\port$26$0 (\$signal$29 )
  );
  sg13g2_a21o_1 \U$120  (
    .A1(\$signal$65 ),
    .A2(\g_new$175 ),
    .B1(\$signal$103 ),
    .X(\g_new$192 )
  );
  sg13g2_a21o_1 \U$121  (
    .A1(\$signal$69 ),
    .A2(\g_new$176 ),
    .B1(\$signal$177 ),
    .X(\$2 )
  );
  sg13g2_xor2_1 \U$122  (
    .A(\$signal ),
    .B(1'h0),
    .X(\$3 )
  );
  sg13g2_xor2_1 \U$123  (
    .A(\$signal$7 ),
    .B(\$signal$73 ),
    .X(\$4 )
  );
  sg13g2_xor2_1 \U$124  (
    .A(\$signal$9 ),
    .B(g_new),
    .X(\$5 )
  );
  sg13g2_xor2_1 \U$125  (
    .A(\$signal$11 ),
    .B(\g_new$178 ),
    .X(\$6 )
  );
  sg13g2_xor2_1 \U$126  (
    .A(\$signal$13 ),
    .B(\g_new$139 ),
    .X(\$7 )
  );
  sg13g2_xor2_1 \U$127  (
    .A(\$signal$15 ),
    .B(\g_new$179 ),
    .X(\$8 )
  );
  sg13g2_xor2_1 \U$128  (
    .A(\$signal$17 ),
    .B(\g_new$169 ),
    .X(\$9 )
  );
  sg13g2_xor2_1 \U$129  (
    .A(\$signal$19 ),
    .B(\g_new$180 ),
    .X(\$10 )
  );
  \adder.U$13  \U$13  (
    .a(a),
    .b(b),
    .\port$27$0 (\$signal$86 ),
    .\port$28$0 (\$signal$31 )
  );
  sg13g2_xor2_1 \U$130  (
    .A(\$signal$21 ),
    .B(\g_new$155 ),
    .X(\$11 )
  );
  sg13g2_xor2_1 \U$131  (
    .A(\$signal$23 ),
    .B(\g_new$181 ),
    .X(\$12 )
  );
  sg13g2_xor2_1 \U$132  (
    .A(\$signal$25 ),
    .B(\g_new$170 ),
    .X(\$13 )
  );
  sg13g2_xor2_1 \U$133  (
    .A(\$signal$27 ),
    .B(\g_new$182 ),
    .X(\$14 )
  );
  sg13g2_xor2_1 \U$134  (
    .A(\$signal$29 ),
    .B(\g_new$166 ),
    .X(\$15 )
  );
  sg13g2_xor2_1 \U$135  (
    .A(\$signal$31 ),
    .B(\g_new$183 ),
    .X(\$16 )
  );
  sg13g2_xor2_1 \U$136  (
    .A(\$signal$33 ),
    .B(\g_new$171 ),
    .X(\$17 )
  );
  sg13g2_xor2_1 \U$137  (
    .A(\$signal$35 ),
    .B(\g_new$184 ),
    .X(\$18 )
  );
  sg13g2_xor2_1 \U$138  (
    .A(\$signal$37 ),
    .B(\g_new$163 ),
    .X(\$19 )
  );
  sg13g2_xor2_1 \U$139  (
    .A(\$signal$39 ),
    .B(\g_new$185 ),
    .X(\$20 )
  );
  \adder.U$14  \U$14  (
    .a(a),
    .b(b),
    .\port$29$0 (\$signal$87 ),
    .\port$30$0 (\$signal$33 )
  );
  sg13g2_xor2_1 \U$140  (
    .A(\$signal$41 ),
    .B(\g_new$172 ),
    .X(\$21 )
  );
  sg13g2_xor2_1 \U$141  (
    .A(\$signal$43 ),
    .B(\g_new$186 ),
    .X(\$22 )
  );
  sg13g2_xor2_1 \U$142  (
    .A(\$signal$45 ),
    .B(\g_new$167 ),
    .X(\$23 )
  );
  sg13g2_xor2_1 \U$143  (
    .A(\$signal$47 ),
    .B(\g_new$187 ),
    .X(\$24 )
  );
  sg13g2_xor2_1 \U$144  (
    .A(\$signal$49 ),
    .B(\g_new$173 ),
    .X(\$25 )
  );
  sg13g2_xor2_1 \U$145  (
    .A(\$signal$51 ),
    .B(\g_new$188 ),
    .X(\$26 )
  );
  sg13g2_xor2_1 \U$146  (
    .A(\$signal$53 ),
    .B(\g_new$165 ),
    .X(\$27 )
  );
  sg13g2_xor2_1 \U$147  (
    .A(\$signal$55 ),
    .B(\g_new$189 ),
    .X(\$28 )
  );
  sg13g2_xor2_1 \U$148  (
    .A(\$signal$57 ),
    .B(\g_new$174 ),
    .X(\$29 )
  );
  sg13g2_xor2_1 \U$149  (
    .A(\$signal$59 ),
    .B(\g_new$190 ),
    .X(\$30 )
  );
  \adder.U$15  \U$15  (
    .a(a),
    .b(b),
    .\port$31$0 (\$signal$88 ),
    .\port$32$0 (\$signal$35 )
  );
  sg13g2_xor2_1 \U$150  (
    .A(\$signal$61 ),
    .B(\g_new$168 ),
    .X(\$31 )
  );
  sg13g2_xor2_1 \U$151  (
    .A(\$signal$63 ),
    .B(\g_new$191 ),
    .X(\$32 )
  );
  sg13g2_xor2_1 \U$152  (
    .A(\$signal$65 ),
    .B(\g_new$175 ),
    .X(\$33 )
  );
  sg13g2_xor2_1 \U$153  (
    .A(\$signal$67 ),
    .B(\g_new$192 ),
    .X(\$34 )
  );
  sg13g2_xor2_1 \U$154  (
    .A(\$signal$69 ),
    .B(\g_new$176 ),
    .X(\$35 )
  );
  \adder.U$16  \U$16  (
    .a(a),
    .b(b),
    .\port$33$0 (\$signal$89 ),
    .\port$34$0 (\$signal$37 )
  );
  \adder.U$17  \U$17  (
    .a(a),
    .b(b),
    .\port$35$0 (\$signal$90 ),
    .\port$36$0 (\$signal$39 )
  );
  \adder.U$18  \U$18  (
    .a(a),
    .b(b),
    .\port$37$0 (\$signal$91 ),
    .\port$38$0 (\$signal$41 )
  );
  \adder.U$19  \U$19  (
    .a(a),
    .b(b),
    .\port$39$0 (\$signal$92 ),
    .\port$40$0 (\$signal$43 )
  );
  \adder.U$2  \U$2  (
    .a(a),
    .b(b),
    .\port$5$0 (\$signal$75 ),
    .\port$6$0 (\$signal$9 )
  );
  \adder.U$20  \U$20  (
    .a(a),
    .b(b),
    .\port$41$0 (\$signal$93 ),
    .\port$42$0 (\$signal$45 )
  );
  \adder.U$21  \U$21  (
    .a(a),
    .b(b),
    .\port$43$0 (\$signal$94 ),
    .\port$44$0 (\$signal$47 )
  );
  \adder.U$22  \U$22  (
    .a(a),
    .b(b),
    .\port$45$0 (\$signal$95 ),
    .\port$46$0 (\$signal$49 )
  );
  \adder.U$23  \U$23  (
    .a(a),
    .b(b),
    .\port$47$0 (\$signal$96 ),
    .\port$48$0 (\$signal$51 )
  );
  \adder.U$24  \U$24  (
    .a(a),
    .b(b),
    .\port$49$0 (\$signal$97 ),
    .\port$50$0 (\$signal$53 )
  );
  \adder.U$25  \U$25  (
    .a(a),
    .b(b),
    .\port$51$0 (\$signal$98 ),
    .\port$52$0 (\$signal$55 )
  );
  \adder.U$26  \U$26  (
    .a(a),
    .b(b),
    .\port$53$0 (\$signal$99 ),
    .\port$54$0 (\$signal$57 )
  );
  \adder.U$27  \U$27  (
    .a(a),
    .b(b),
    .\port$55$0 (\$signal$100 ),
    .\port$56$0 (\$signal$59 )
  );
  \adder.U$28  \U$28  (
    .a(a),
    .b(b),
    .\port$57$0 (\$signal$101 ),
    .\port$58$0 (\$signal$61 )
  );
  \adder.U$29  \U$29  (
    .a(a),
    .b(b),
    .\port$59$0 (\$signal$102 ),
    .\port$60$0 (\$signal$63 )
  );
  \adder.U$3  \U$3  (
    .a(a),
    .b(b),
    .\port$7$0 (\$signal$76 ),
    .\port$8$0 (\$signal$11 )
  );
  \adder.U$30  \U$30  (
    .a(a),
    .b(b),
    .\port$61$0 (\$signal$103 ),
    .\port$62$0 (\$signal$65 )
  );
  \adder.U$31  \U$31  (
    .a(a),
    .b(b),
    .\port$63$0 (\$signal$104 ),
    .\port$64$0 (\$signal$67 )
  );
  \adder.U$32  \U$32  (
    .a(a),
    .b(b),
    .\port$65$0 (\$signal$177 ),
    .\port$66$0 (\$signal$69 )
  );
  sg13g2_and2_1 \U$33  (
    .A(\$signal$7 ),
    .B(\$signal ),
    .X(\p_new$106 )
  );
  sg13g2_a21o_1 \U$34  (
    .A1(\$signal$7 ),
    .A2(\$signal$73 ),
    .B1(\$signal$74 ),
    .X(g_new)
  );
  sg13g2_and2_1 \U$35  (
    .A(\$signal$11 ),
    .B(\$signal$9 ),
    .X(p_new)
  );
  sg13g2_a21o_1 \U$36  (
    .A1(\$signal$11 ),
    .A2(\$signal$75 ),
    .B1(\$signal$76 ),
    .X(\g_new$108 )
  );
  sg13g2_and2_1 \U$37  (
    .A(\$signal$15 ),
    .B(\$signal$13 ),
    .X(\p_new$110 )
  );
  sg13g2_a21o_1 \U$38  (
    .A1(\$signal$15 ),
    .A2(\$signal$77 ),
    .B1(\$signal$78 ),
    .X(\g_new$111 )
  );
  sg13g2_and2_1 \U$39  (
    .A(\$signal$19 ),
    .B(\$signal$17 ),
    .X(\p_new$109 )
  );
  \adder.U$4  \U$4  (
    .a(a),
    .b(b),
    .\port$10$0 (\$signal$13 ),
    .\port$9$0 (\$signal$77 )
  );
  sg13g2_a21o_1 \U$40  (
    .A1(\$signal$19 ),
    .A2(\$signal$79 ),
    .B1(\$signal$80 ),
    .X(\g_new$112 )
  );
  sg13g2_and2_1 \U$41  (
    .A(\$signal$23 ),
    .B(\$signal$21 ),
    .X(\p_new$114 )
  );
  sg13g2_a21o_1 \U$42  (
    .A1(\$signal$23 ),
    .A2(\$signal$81 ),
    .B1(\$signal$82 ),
    .X(\g_new$115 )
  );
  sg13g2_and2_1 \U$43  (
    .A(\$signal$27 ),
    .B(\$signal$25 ),
    .X(\p_new$113 )
  );
  sg13g2_a21o_1 \U$44  (
    .A1(\$signal$27 ),
    .A2(\$signal$83 ),
    .B1(\$signal$84 ),
    .X(\g_new$116 )
  );
  sg13g2_and2_1 \U$45  (
    .A(\$signal$31 ),
    .B(\$signal$29 ),
    .X(\p_new$118 )
  );
  sg13g2_a21o_1 \U$46  (
    .A1(\$signal$31 ),
    .A2(\$signal$85 ),
    .B1(\$signal$86 ),
    .X(\g_new$119 )
  );
  sg13g2_and2_1 \U$47  (
    .A(\$signal$35 ),
    .B(\$signal$33 ),
    .X(\p_new$117 )
  );
  sg13g2_a21o_1 \U$48  (
    .A1(\$signal$35 ),
    .A2(\$signal$87 ),
    .B1(\$signal$88 ),
    .X(\g_new$120 )
  );
  sg13g2_and2_1 \U$49  (
    .A(\$signal$39 ),
    .B(\$signal$37 ),
    .X(\p_new$122 )
  );
  \adder.U$5  \U$5  (
    .a(a),
    .b(b),
    .\port$11$0 (\$signal$78 ),
    .\port$12$0 (\$signal$15 )
  );
  sg13g2_a21o_1 \U$50  (
    .A1(\$signal$39 ),
    .A2(\$signal$89 ),
    .B1(\$signal$90 ),
    .X(\g_new$123 )
  );
  sg13g2_and2_1 \U$51  (
    .A(\$signal$43 ),
    .B(\$signal$41 ),
    .X(\p_new$121 )
  );
  sg13g2_a21o_1 \U$52  (
    .A1(\$signal$43 ),
    .A2(\$signal$91 ),
    .B1(\$signal$92 ),
    .X(\g_new$124 )
  );
  sg13g2_and2_1 \U$53  (
    .A(\$signal$47 ),
    .B(\$signal$45 ),
    .X(\p_new$126 )
  );
  sg13g2_a21o_1 \U$54  (
    .A1(\$signal$47 ),
    .A2(\$signal$93 ),
    .B1(\$signal$94 ),
    .X(\g_new$127 )
  );
  sg13g2_and2_1 \U$55  (
    .A(\$signal$51 ),
    .B(\$signal$49 ),
    .X(\p_new$125 )
  );
  sg13g2_a21o_1 \U$56  (
    .A1(\$signal$51 ),
    .A2(\$signal$95 ),
    .B1(\$signal$96 ),
    .X(\g_new$128 )
  );
  sg13g2_and2_1 \U$57  (
    .A(\$signal$55 ),
    .B(\$signal$53 ),
    .X(\p_new$130 )
  );
  sg13g2_a21o_1 \U$58  (
    .A1(\$signal$55 ),
    .A2(\$signal$97 ),
    .B1(\$signal$98 ),
    .X(\g_new$131 )
  );
  sg13g2_and2_1 \U$59  (
    .A(\$signal$59 ),
    .B(\$signal$57 ),
    .X(\p_new$129 )
  );
  \adder.U$6  \U$6  (
    .a(a),
    .b(b),
    .\port$13$0 (\$signal$79 ),
    .\port$14$0 (\$signal$17 )
  );
  sg13g2_a21o_1 \U$60  (
    .A1(\$signal$59 ),
    .A2(\$signal$99 ),
    .B1(\$signal$100 ),
    .X(\g_new$132 )
  );
  sg13g2_and2_1 \U$61  (
    .A(\$signal$63 ),
    .B(\$signal$61 ),
    .X(\p_new$134 )
  );
  sg13g2_a21o_1 \U$62  (
    .A1(\$signal$63 ),
    .A2(\$signal$101 ),
    .B1(\$signal$102 ),
    .X(\g_new$135 )
  );
  sg13g2_and2_1 \U$63  (
    .A(\$signal$67 ),
    .B(\$signal$65 ),
    .X(\p_new$133 )
  );
  sg13g2_a21o_1 \U$64  (
    .A1(\$signal$67 ),
    .A2(\$signal$103 ),
    .B1(\$signal$104 ),
    .X(\g_new$136 )
  );
  sg13g2_and2_1 \U$65  (
    .A(p_new),
    .B(\p_new$106 ),
    .X(\p_new$138 )
  );
  sg13g2_a21o_1 \U$66  (
    .A1(p_new),
    .A2(g_new),
    .B1(\g_new$108 ),
    .X(\g_new$139 )
  );
  sg13g2_and2_1 \U$67  (
    .A(\p_new$109 ),
    .B(\p_new$110 ),
    .X(\p_new$137 )
  );
  sg13g2_a21o_1 \U$68  (
    .A1(\p_new$109 ),
    .A2(\g_new$111 ),
    .B1(\g_new$112 ),
    .X(\g_new$140 )
  );
  sg13g2_and2_1 \U$69  (
    .A(\p_new$113 ),
    .B(\p_new$114 ),
    .X(\p_new$142 )
  );
  \adder.U$7  \U$7  (
    .a(a),
    .b(b),
    .\port$15$0 (\$signal$80 ),
    .\port$16$0 (\$signal$19 )
  );
  sg13g2_a21o_1 \U$70  (
    .A1(\p_new$113 ),
    .A2(\g_new$115 ),
    .B1(\g_new$116 ),
    .X(\g_new$143 )
  );
  sg13g2_and2_1 \U$71  (
    .A(\p_new$117 ),
    .B(\p_new$118 ),
    .X(\p_new$141 )
  );
  sg13g2_a21o_1 \U$72  (
    .A1(\p_new$117 ),
    .A2(\g_new$119 ),
    .B1(\g_new$120 ),
    .X(\g_new$144 )
  );
  sg13g2_and2_1 \U$73  (
    .A(\p_new$121 ),
    .B(\p_new$122 ),
    .X(\p_new$146 )
  );
  sg13g2_a21o_1 \U$74  (
    .A1(\p_new$121 ),
    .A2(\g_new$123 ),
    .B1(\g_new$124 ),
    .X(\g_new$147 )
  );
  sg13g2_and2_1 \U$75  (
    .A(\p_new$125 ),
    .B(\p_new$126 ),
    .X(\p_new$145 )
  );
  sg13g2_a21o_1 \U$76  (
    .A1(\p_new$125 ),
    .A2(\g_new$127 ),
    .B1(\g_new$128 ),
    .X(\g_new$148 )
  );
  sg13g2_and2_1 \U$77  (
    .A(\p_new$129 ),
    .B(\p_new$130 ),
    .X(\p_new$150 )
  );
  sg13g2_a21o_1 \U$78  (
    .A1(\p_new$129 ),
    .A2(\g_new$131 ),
    .B1(\g_new$132 ),
    .X(\g_new$151 )
  );
  sg13g2_and2_1 \U$79  (
    .A(\p_new$133 ),
    .B(\p_new$134 ),
    .X(\p_new$149 )
  );
  \adder.U$8  \U$8  (
    .a(a),
    .b(b),
    .\port$17$0 (\$signal$81 ),
    .\port$18$0 (\$signal$21 )
  );
  sg13g2_a21o_1 \U$80  (
    .A1(\p_new$133 ),
    .A2(\g_new$135 ),
    .B1(\g_new$136 ),
    .X(\g_new$152 )
  );
  sg13g2_and2_1 \U$81  (
    .A(\p_new$137 ),
    .B(\p_new$138 ),
    .X(\p_new$154 )
  );
  sg13g2_a21o_1 \U$82  (
    .A1(\p_new$137 ),
    .A2(\g_new$139 ),
    .B1(\g_new$140 ),
    .X(\g_new$155 )
  );
  sg13g2_and2_1 \U$83  (
    .A(\p_new$141 ),
    .B(\p_new$142 ),
    .X(\p_new$153 )
  );
  sg13g2_a21o_1 \U$84  (
    .A1(\p_new$141 ),
    .A2(\g_new$143 ),
    .B1(\g_new$144 ),
    .X(\g_new$156 )
  );
  sg13g2_and2_1 \U$85  (
    .A(\p_new$145 ),
    .B(\p_new$146 ),
    .X(\p_new$158 )
  );
  sg13g2_a21o_1 \U$86  (
    .A1(\p_new$145 ),
    .A2(\g_new$147 ),
    .B1(\g_new$148 ),
    .X(\g_new$159 )
  );
  sg13g2_and2_1 \U$87  (
    .A(\p_new$149 ),
    .B(\p_new$150 ),
    .X(\p_new$157 )
  );
  sg13g2_a21o_1 \U$88  (
    .A1(\p_new$149 ),
    .A2(\g_new$151 ),
    .B1(\g_new$152 ),
    .X(\g_new$160 )
  );
  sg13g2_and2_1 \U$89  (
    .A(\p_new$153 ),
    .B(\p_new$154 ),
    .X(\p_new$162 )
  );
  \adder.U$9  \U$9  (
    .a(a),
    .b(b),
    .\port$19$0 (\$signal$82 ),
    .\port$20$0 (\$signal$23 )
  );
  sg13g2_a21o_1 \U$90  (
    .A1(\p_new$153 ),
    .A2(\g_new$155 ),
    .B1(\g_new$156 ),
    .X(\g_new$163 )
  );
  sg13g2_and2_1 \U$91  (
    .A(\p_new$157 ),
    .B(\p_new$158 ),
    .X(\p_new$161 )
  );
  sg13g2_a21o_1 \U$92  (
    .A1(\p_new$157 ),
    .A2(\g_new$159 ),
    .B1(\g_new$160 ),
    .X(\g_new$164 )
  );
  sg13g2_and2_1 \U$93  (
    .A(\p_new$161 ),
    .B(\p_new$162 ),
    .X(\$1 )
  );
  sg13g2_a21o_1 \U$94  (
    .A1(\p_new$161 ),
    .A2(\g_new$163 ),
    .B1(\g_new$164 ),
    .X(\g_new$176 )
  );
  sg13g2_a21o_1 \U$95  (
    .A1(\p_new$158 ),
    .A2(\g_new$163 ),
    .B1(\g_new$159 ),
    .X(\g_new$165 )
  );
  sg13g2_a21o_1 \U$96  (
    .A1(\p_new$142 ),
    .A2(\g_new$155 ),
    .B1(\g_new$143 ),
    .X(\g_new$166 )
  );
  sg13g2_a21o_1 \U$97  (
    .A1(\p_new$146 ),
    .A2(\g_new$163 ),
    .B1(\g_new$147 ),
    .X(\g_new$167 )
  );
  sg13g2_a21o_1 \U$98  (
    .A1(\p_new$150 ),
    .A2(\g_new$165 ),
    .B1(\g_new$151 ),
    .X(\g_new$168 )
  );
  sg13g2_a21o_1 \U$99  (
    .A1(\p_new$110 ),
    .A2(\g_new$139 ),
    .B1(\g_new$111 ),
    .X(\g_new$169 )
  );
  assign \a$3  = a;
  assign \b$4  = b;
  assign \$signal$6  = \$signal ;
  assign \$signal$8  = \$signal$7 ;
  assign \$signal$10  = \$signal$9 ;
  assign \$signal$12  = \$signal$11 ;
  assign \$signal$14  = \$signal$13 ;
  assign \$signal$16  = \$signal$15 ;
  assign \$signal$18  = \$signal$17 ;
  assign \$signal$20  = \$signal$19 ;
  assign \$signal$22  = \$signal$21 ;
  assign \$signal$24  = \$signal$23 ;
  assign \$signal$26  = \$signal$25 ;
  assign \$signal$28  = \$signal$27 ;
  assign \$signal$30  = \$signal$29 ;
  assign \$signal$32  = \$signal$31 ;
  assign \$signal$34  = \$signal$33 ;
  assign \$signal$36  = \$signal$35 ;
  assign \$signal$38  = \$signal$37 ;
  assign \$signal$40  = \$signal$39 ;
  assign \$signal$42  = \$signal$41 ;
  assign \$signal$44  = \$signal$43 ;
  assign \$signal$46  = \$signal$45 ;
  assign \$signal$48  = \$signal$47 ;
  assign \$signal$50  = \$signal$49 ;
  assign \$signal$52  = \$signal$51 ;
  assign \$signal$54  = \$signal$53 ;
  assign \$signal$56  = \$signal$55 ;
  assign \$signal$58  = \$signal$57 ;
  assign \$signal$60  = \$signal$59 ;
  assign \$signal$62  = \$signal$61 ;
  assign \$signal$64  = \$signal$63 ;
  assign \$signal$66  = \$signal$65 ;
  assign \$signal$68  = \$signal$67 ;
  assign \$signal$70  = \$signal$69 ;
  assign o2 = { \$35 , \$34 , \$33 , \$32 , \$31 , \$30 , \$29 , \$28 , \$27 , \$26 , \$25 , \$24 , \$23 , \$22 , \$21 , \$20 , \$19 , \$18 , \$17 , \$16 , \$15 , \$14 , \$13 , \$12 , \$11 , \$10 , \$9 , \$8 , \$7 , \$6 , \$5 , \$4 , \$3  };
  assign \o$72  = { \$35 , \$34 , \$33 , \$32 , \$31 , \$30 , \$29 , \$28 , \$27 , \$26 , \$25 , \$24 , \$23 , \$22 , \$21 , \$20 , \$19 , \$18 , \$17 , \$16 , \$15 , \$14 , \$13 , \$12 , \$11 , \$10 , \$9 , \$8 , \$7 , \$6 , \$5 , \$4 , \$3  };
  assign o = { \$35 , \$34 , \$33 , \$32 , \$31 , \$30 , \$29 , \$28 , \$27 , \$26 , \$25 , \$24 , \$23 , \$22 , \$21 , \$20 , \$19 , \$18 , \$17 , \$16 , \$15 , \$14 , \$13 , \$12 , \$11 , \$10 , \$9 , \$8 , \$7 , \$6 , \$5 , \$4 , \$3  };
endmodule

module \adder.U$0 (b, \port$1$0 , \port$2$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$1$0 ;
  wire \port$1$0 ;
  output \port$2$0 ;
  wire \port$2$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[0]),
    .B(b[0]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[0]),
    .B(b[0]),
    .X(\$signal )
  );
  assign \port$1$0  = \$signal$3 ;
  assign \port$2$0  = \$signal ;
endmodule

module \adder.U$1 (b, \port$3$0 , \port$4$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$3$0 ;
  wire \port$3$0 ;
  output \port$4$0 ;
  wire \port$4$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[1]),
    .B(b[1]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[1]),
    .B(b[1]),
    .X(\$signal )
  );
  assign \port$3$0  = \$signal$3 ;
  assign \port$4$0  = \$signal ;
endmodule

module \adder.U$10 (b, \port$21$0 , \port$22$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$21$0 ;
  wire \port$21$0 ;
  output \port$22$0 ;
  wire \port$22$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[10]),
    .B(b[10]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[10]),
    .B(b[10]),
    .X(\$signal )
  );
  assign \port$21$0  = \$signal$3 ;
  assign \port$22$0  = \$signal ;
endmodule

module \adder.U$11 (b, \port$23$0 , \port$24$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$23$0 ;
  wire \port$23$0 ;
  output \port$24$0 ;
  wire \port$24$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[11]),
    .B(b[11]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[11]),
    .B(b[11]),
    .X(\$signal )
  );
  assign \port$23$0  = \$signal$3 ;
  assign \port$24$0  = \$signal ;
endmodule

module \adder.U$12 (b, \port$25$0 , \port$26$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$25$0 ;
  wire \port$25$0 ;
  output \port$26$0 ;
  wire \port$26$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[12]),
    .B(b[12]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[12]),
    .B(b[12]),
    .X(\$signal )
  );
  assign \port$25$0  = \$signal$3 ;
  assign \port$26$0  = \$signal ;
endmodule

module \adder.U$13 (b, \port$27$0 , \port$28$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$27$0 ;
  wire \port$27$0 ;
  output \port$28$0 ;
  wire \port$28$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[13]),
    .B(b[13]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[13]),
    .B(b[13]),
    .X(\$signal )
  );
  assign \port$27$0  = \$signal$3 ;
  assign \port$28$0  = \$signal ;
endmodule

module \adder.U$14 (b, \port$29$0 , \port$30$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$29$0 ;
  wire \port$29$0 ;
  output \port$30$0 ;
  wire \port$30$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[14]),
    .B(b[14]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[14]),
    .B(b[14]),
    .X(\$signal )
  );
  assign \port$29$0  = \$signal$3 ;
  assign \port$30$0  = \$signal ;
endmodule

module \adder.U$15 (b, \port$31$0 , \port$32$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$31$0 ;
  wire \port$31$0 ;
  output \port$32$0 ;
  wire \port$32$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[15]),
    .B(b[15]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[15]),
    .B(b[15]),
    .X(\$signal )
  );
  assign \port$31$0  = \$signal$3 ;
  assign \port$32$0  = \$signal ;
endmodule

module \adder.U$16 (b, \port$33$0 , \port$34$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$33$0 ;
  wire \port$33$0 ;
  output \port$34$0 ;
  wire \port$34$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[16]),
    .B(b[16]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[16]),
    .B(b[16]),
    .X(\$signal )
  );
  assign \port$33$0  = \$signal$3 ;
  assign \port$34$0  = \$signal ;
endmodule

module \adder.U$17 (b, \port$35$0 , \port$36$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$35$0 ;
  wire \port$35$0 ;
  output \port$36$0 ;
  wire \port$36$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[17]),
    .B(b[17]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[17]),
    .B(b[17]),
    .X(\$signal )
  );
  assign \port$35$0  = \$signal$3 ;
  assign \port$36$0  = \$signal ;
endmodule

module \adder.U$18 (b, \port$37$0 , \port$38$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$37$0 ;
  wire \port$37$0 ;
  output \port$38$0 ;
  wire \port$38$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[18]),
    .B(b[18]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[18]),
    .B(b[18]),
    .X(\$signal )
  );
  assign \port$37$0  = \$signal$3 ;
  assign \port$38$0  = \$signal ;
endmodule

module \adder.U$19 (b, \port$39$0 , \port$40$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$39$0 ;
  wire \port$39$0 ;
  output \port$40$0 ;
  wire \port$40$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[19]),
    .B(b[19]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[19]),
    .B(b[19]),
    .X(\$signal )
  );
  assign \port$39$0  = \$signal$3 ;
  assign \port$40$0  = \$signal ;
endmodule

module \adder.U$2 (b, \port$5$0 , \port$6$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$5$0 ;
  wire \port$5$0 ;
  output \port$6$0 ;
  wire \port$6$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[2]),
    .B(b[2]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[2]),
    .B(b[2]),
    .X(\$signal )
  );
  assign \port$5$0  = \$signal$3 ;
  assign \port$6$0  = \$signal ;
endmodule

module \adder.U$20 (b, \port$41$0 , \port$42$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$41$0 ;
  wire \port$41$0 ;
  output \port$42$0 ;
  wire \port$42$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[20]),
    .B(b[20]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[20]),
    .B(b[20]),
    .X(\$signal )
  );
  assign \port$41$0  = \$signal$3 ;
  assign \port$42$0  = \$signal ;
endmodule

module \adder.U$21 (b, \port$43$0 , \port$44$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$43$0 ;
  wire \port$43$0 ;
  output \port$44$0 ;
  wire \port$44$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[21]),
    .B(b[21]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[21]),
    .B(b[21]),
    .X(\$signal )
  );
  assign \port$43$0  = \$signal$3 ;
  assign \port$44$0  = \$signal ;
endmodule

module \adder.U$22 (b, \port$45$0 , \port$46$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$45$0 ;
  wire \port$45$0 ;
  output \port$46$0 ;
  wire \port$46$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[22]),
    .B(b[22]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[22]),
    .B(b[22]),
    .X(\$signal )
  );
  assign \port$45$0  = \$signal$3 ;
  assign \port$46$0  = \$signal ;
endmodule

module \adder.U$23 (b, \port$47$0 , \port$48$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$47$0 ;
  wire \port$47$0 ;
  output \port$48$0 ;
  wire \port$48$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[23]),
    .B(b[23]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[23]),
    .B(b[23]),
    .X(\$signal )
  );
  assign \port$47$0  = \$signal$3 ;
  assign \port$48$0  = \$signal ;
endmodule

module \adder.U$24 (b, \port$49$0 , \port$50$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$49$0 ;
  wire \port$49$0 ;
  output \port$50$0 ;
  wire \port$50$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[24]),
    .B(b[24]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[24]),
    .B(b[24]),
    .X(\$signal )
  );
  assign \port$49$0  = \$signal$3 ;
  assign \port$50$0  = \$signal ;
endmodule

module \adder.U$25 (b, \port$51$0 , \port$52$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$51$0 ;
  wire \port$51$0 ;
  output \port$52$0 ;
  wire \port$52$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[25]),
    .B(b[25]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[25]),
    .B(b[25]),
    .X(\$signal )
  );
  assign \port$51$0  = \$signal$3 ;
  assign \port$52$0  = \$signal ;
endmodule

module \adder.U$26 (b, \port$53$0 , \port$54$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$53$0 ;
  wire \port$53$0 ;
  output \port$54$0 ;
  wire \port$54$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[26]),
    .B(b[26]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[26]),
    .B(b[26]),
    .X(\$signal )
  );
  assign \port$53$0  = \$signal$3 ;
  assign \port$54$0  = \$signal ;
endmodule

module \adder.U$27 (b, \port$55$0 , \port$56$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$55$0 ;
  wire \port$55$0 ;
  output \port$56$0 ;
  wire \port$56$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[27]),
    .B(b[27]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[27]),
    .B(b[27]),
    .X(\$signal )
  );
  assign \port$55$0  = \$signal$3 ;
  assign \port$56$0  = \$signal ;
endmodule

module \adder.U$28 (b, \port$57$0 , \port$58$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$57$0 ;
  wire \port$57$0 ;
  output \port$58$0 ;
  wire \port$58$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[28]),
    .B(b[28]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[28]),
    .B(b[28]),
    .X(\$signal )
  );
  assign \port$57$0  = \$signal$3 ;
  assign \port$58$0  = \$signal ;
endmodule

module \adder.U$29 (b, \port$59$0 , \port$60$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$59$0 ;
  wire \port$59$0 ;
  output \port$60$0 ;
  wire \port$60$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[29]),
    .B(b[29]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[29]),
    .B(b[29]),
    .X(\$signal )
  );
  assign \port$59$0  = \$signal$3 ;
  assign \port$60$0  = \$signal ;
endmodule

module \adder.U$3 (b, \port$7$0 , \port$8$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$7$0 ;
  wire \port$7$0 ;
  output \port$8$0 ;
  wire \port$8$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[3]),
    .B(b[3]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[3]),
    .B(b[3]),
    .X(\$signal )
  );
  assign \port$7$0  = \$signal$3 ;
  assign \port$8$0  = \$signal ;
endmodule

module \adder.U$30 (b, \port$61$0 , \port$62$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$61$0 ;
  wire \port$61$0 ;
  output \port$62$0 ;
  wire \port$62$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[30]),
    .B(b[30]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[30]),
    .B(b[30]),
    .X(\$signal )
  );
  assign \port$61$0  = \$signal$3 ;
  assign \port$62$0  = \$signal ;
endmodule

module \adder.U$31 (b, \port$63$0 , \port$64$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$63$0 ;
  wire \port$63$0 ;
  output \port$64$0 ;
  wire \port$64$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[31]),
    .B(b[31]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[31]),
    .B(b[31]),
    .X(\$signal )
  );
  assign \port$63$0  = \$signal$3 ;
  assign \port$64$0  = \$signal ;
endmodule

module \adder.U$32 (b, \port$65$0 , \port$66$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$65$0 ;
  wire \port$65$0 ;
  output \port$66$0 ;
  wire \port$66$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[32]),
    .B(b[32]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[32]),
    .B(b[32]),
    .X(\$signal )
  );
  assign \port$65$0  = \$signal$3 ;
  assign \port$66$0  = \$signal ;
endmodule

module \adder.U$4 (b, \port$9$0 , \port$10$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$10$0 ;
  wire \port$10$0 ;
  output \port$9$0 ;
  wire \port$9$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[4]),
    .B(b[4]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[4]),
    .B(b[4]),
    .X(\$signal )
  );
  assign \port$9$0  = \$signal$3 ;
  assign \port$10$0  = \$signal ;
endmodule

module \adder.U$5 (b, \port$11$0 , \port$12$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$11$0 ;
  wire \port$11$0 ;
  output \port$12$0 ;
  wire \port$12$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[5]),
    .B(b[5]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[5]),
    .B(b[5]),
    .X(\$signal )
  );
  assign \port$11$0  = \$signal$3 ;
  assign \port$12$0  = \$signal ;
endmodule

module \adder.U$6 (b, \port$13$0 , \port$14$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$13$0 ;
  wire \port$13$0 ;
  output \port$14$0 ;
  wire \port$14$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[6]),
    .B(b[6]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[6]),
    .B(b[6]),
    .X(\$signal )
  );
  assign \port$13$0  = \$signal$3 ;
  assign \port$14$0  = \$signal ;
endmodule

module \adder.U$7 (b, \port$15$0 , \port$16$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$15$0 ;
  wire \port$15$0 ;
  output \port$16$0 ;
  wire \port$16$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[7]),
    .B(b[7]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[7]),
    .B(b[7]),
    .X(\$signal )
  );
  assign \port$15$0  = \$signal$3 ;
  assign \port$16$0  = \$signal ;
endmodule

module \adder.U$8 (b, \port$17$0 , \port$18$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$17$0 ;
  wire \port$17$0 ;
  output \port$18$0 ;
  wire \port$18$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[8]),
    .B(b[8]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[8]),
    .B(b[8]),
    .X(\$signal )
  );
  assign \port$17$0  = \$signal$3 ;
  assign \port$18$0  = \$signal ;
endmodule

module \adder.U$9 (b, \port$19$0 , \port$20$0 , a);
  wire \$signal ;
  wire \$signal$3 ;
  input [32:0] a;
  wire [32:0] a;
  input [32:0] b;
  wire [32:0] b;
  output \port$19$0 ;
  wire \port$19$0 ;
  output \port$20$0 ;
  wire \port$20$0 ;
  sg13g2_and2_1 ha_inst_0 (
    .A(a[9]),
    .B(b[9]),
    .X(\$signal$3 )
  );
  sg13g2_xor2_1 ha_inst_1 (
    .A(a[9]),
    .B(b[9]),
    .X(\$signal )
  );
  assign \port$19$0  = \$signal$3 ;
  assign \port$20$0  = \$signal ;
endmodule
