// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module fault_monitor_reg_top #(
        parameter ID_WIDTH = 1
    ) (
        input wire clk,
        input wire arst_n,

        input wire obi_req,
        output logic obi_gnt,
        input wire [5:0] obi_addr,
        input wire obi_we,
        input wire [3:0] obi_be,
        input wire [31:0] obi_wdata,
        input wire [ID_WIDTH-1:0] obi_aid,
        output logic obi_rvalid,
        input wire obi_rready,
        output logic [31:0] obi_rdata,
        output logic obi_err,
        output logic [ID_WIDTH-1:0] obi_rid,

        input fault_monitor_reg_pkg::fault_monitor__in_t hwif_in
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [5:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // State & holding regs
    logic is_active; // A request is being served (not yet fully responded)
    logic gnt_q; // one-cycle grant for A-channel
    logic rsp_pending; // response ready but not yet accepted by manager
    logic [31:0] rsp_rdata_q;
    logic rsp_err_q;
    logic [$bits(obi_rid)-1:0] rid_q;

    // Latch AID on accept to echo back the response
    always_ff @(posedge clk or negedge arst_n) begin
        if (~arst_n) begin
            is_active <= 1'b0;
            gnt_q <= 1'b0;
            rsp_pending <= 1'b0;
            rsp_rdata_q <= '0;
            rsp_err_q <= 1'b0;
            rid_q <= '0;

            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            // defaults
            cpuif_req <= 1'b0;
            gnt_q <= obi_req & ~is_active;

            // Accept new request when idle
            if (~is_active) begin
                if (obi_req) begin
                    is_active <= 1'b1;
                    cpuif_req <= 1'b1;
                    cpuif_req_is_wr <= obi_we;
                    cpuif_addr <= obi_addr;
                    cpuif_wr_data <= obi_wdata;
                    rid_q <= obi_aid;
                    for (int i = 0; i < 4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{ obi_be[i] }};
                    end
                end
            end

            // Capture response
            if (is_active && (cpuif_rd_ack || cpuif_wr_ack)) begin
                rsp_pending <= 1'b1;
                rsp_rdata_q <= cpuif_rd_data;
                rsp_err_q <= cpuif_rd_err | cpuif_wr_err;
                // NOTE: Keep 'is_active' asserted until the external R handshake completes
            end

            // Complete external R-channel handshake only if manager ready
            if (rsp_pending && obi_rvalid && obi_rready) begin
                rsp_pending <= 1'b0;
                is_active <= 1'b0; // free to accept the next request
            end
        end
    end

    // R-channel outputs (held stable while rsp_pending=1)
    assign obi_rvalid = rsp_pending;
    assign obi_rdata = rsp_rdata_q;
    assign obi_err = rsp_err_q;
    assign obi_rid = rid_q;

    // A-channel grant (registered one-cycle pulse when we accept a request)
    assign obi_gnt = gnt_q;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic relobi_correctable_fault;
        logic relobi_uncorrectable_fault;
        logic core_ctrl_correctable_fault;
        logic core_ctrl_uncorrectable_fault;
        logic uart_fault;
        logic gpio_fault;
        logic timer_fault;
        logic sram_scrub_correctable[2];
        logic sram_scrub_uncorrectable[2];
        logic sram_correctable_fault[2];
        logic sram_uncorrectable_fault[2];
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.relobi_correctable_fault = cpuif_req_masked & (cpuif_addr == 6'h0);
        decoded_reg_strb.relobi_uncorrectable_fault = cpuif_req_masked & (cpuif_addr == 6'h4);
        decoded_reg_strb.core_ctrl_correctable_fault = cpuif_req_masked & (cpuif_addr == 6'h8);
        decoded_reg_strb.core_ctrl_uncorrectable_fault = cpuif_req_masked & (cpuif_addr == 6'hc);
        decoded_reg_strb.uart_fault = cpuif_req_masked & (cpuif_addr == 6'h10);
        decoded_reg_strb.gpio_fault = cpuif_req_masked & (cpuif_addr == 6'h14);
        decoded_reg_strb.timer_fault = cpuif_req_masked & (cpuif_addr == 6'h18);
        for(int i0=0; i0<2; i0++) begin
            decoded_reg_strb.sram_scrub_correctable[i0] = cpuif_req_masked & (cpuif_addr == 6'h1c + (6)'(i0) * 6'h4);
        end
        for(int i0=0; i0<2; i0++) begin
            decoded_reg_strb.sram_scrub_uncorrectable[i0] = cpuif_req_masked & (cpuif_addr == 6'h24 + (6)'(i0) * 6'h4);
        end
        for(int i0=0; i0<2; i0++) begin
            decoded_reg_strb.sram_correctable_fault[i0] = cpuif_req_masked & (cpuif_addr == 6'h2c + (6)'(i0) * 6'h4);
        end
        for(int i0=0; i0<2; i0++) begin
            decoded_reg_strb.sram_uncorrectable_fault[i0] = cpuif_req_masked & (cpuif_addr == 6'h34 + (6)'(i0) * 6'h4);
        end
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } fault_count;
        } relobi_correctable_fault;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } fault_count;
        } relobi_uncorrectable_fault;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } fault_count;
        } core_ctrl_correctable_fault;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } fault_count;
        } core_ctrl_uncorrectable_fault;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } fault_count;
        } uart_fault;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } fault_count;
        } gpio_fault;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } fault_count;
        } timer_fault;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } fault_count;
        } sram_scrub_correctable[2];
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } fault_count;
        } sram_scrub_uncorrectable[2];
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } fault_count;
        } sram_correctable_fault[2];
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
                logic incrthreshold;
                logic overflow;
            } fault_count;
        } sram_uncorrectable_fault[2];
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [31:0] value;
            } fault_count;
        } relobi_correctable_fault;
        struct {
            struct {
                logic [31:0] value;
            } fault_count;
        } relobi_uncorrectable_fault;
        struct {
            struct {
                logic [31:0] value;
            } fault_count;
        } core_ctrl_correctable_fault;
        struct {
            struct {
                logic [31:0] value;
            } fault_count;
        } core_ctrl_uncorrectable_fault;
        struct {
            struct {
                logic [31:0] value;
            } fault_count;
        } uart_fault;
        struct {
            struct {
                logic [31:0] value;
            } fault_count;
        } gpio_fault;
        struct {
            struct {
                logic [31:0] value;
            } fault_count;
        } timer_fault;
        struct {
            struct {
                logic [31:0] value;
            } fault_count;
        } sram_scrub_correctable[2];
        struct {
            struct {
                logic [31:0] value;
            } fault_count;
        } sram_scrub_uncorrectable[2];
        struct {
            struct {
                logic [31:0] value;
            } fault_count;
        } sram_correctable_fault[2];
        struct {
            struct {
                logic [31:0] value;
            } fault_count;
        } sram_uncorrectable_fault[2];
    } field_storage_t;
    field_storage_t field_storage;

    // Field: fault_monitor.relobi_correctable_fault.fault_count
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.relobi_correctable_fault.fault_count.value;
        load_next_c = '0;
        if(decoded_reg_strb.relobi_correctable_fault && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.relobi_correctable_fault.fault_count.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        if(hwif_in.relobi_correctable_fault.fault_count.incr) begin // increment
            field_combo.relobi_correctable_fault.fault_count.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
            next_c = next_c + 32'h1;
            load_next_c = '1;
        end else begin
            field_combo.relobi_correctable_fault.fault_count.overflow = '0;
        end
        field_combo.relobi_correctable_fault.fault_count.incrthreshold = (field_storage.relobi_correctable_fault.fault_count.value >= 32'hffffffff);
        field_combo.relobi_correctable_fault.fault_count.next = next_c;
        field_combo.relobi_correctable_fault.fault_count.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.relobi_correctable_fault.fault_count.value <= 32'h0;
        end else begin
            if(field_combo.relobi_correctable_fault.fault_count.load_next) begin
                field_storage.relobi_correctable_fault.fault_count.value <= field_combo.relobi_correctable_fault.fault_count.next;
            end
        end
    end
    // Field: fault_monitor.relobi_uncorrectable_fault.fault_count
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.relobi_uncorrectable_fault.fault_count.value;
        load_next_c = '0;
        if(decoded_reg_strb.relobi_uncorrectable_fault && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.relobi_uncorrectable_fault.fault_count.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        if(hwif_in.relobi_uncorrectable_fault.fault_count.incr) begin // increment
            field_combo.relobi_uncorrectable_fault.fault_count.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
            next_c = next_c + 32'h1;
            load_next_c = '1;
        end else begin
            field_combo.relobi_uncorrectable_fault.fault_count.overflow = '0;
        end
        field_combo.relobi_uncorrectable_fault.fault_count.incrthreshold = (field_storage.relobi_uncorrectable_fault.fault_count.value >= 32'hffffffff);
        field_combo.relobi_uncorrectable_fault.fault_count.next = next_c;
        field_combo.relobi_uncorrectable_fault.fault_count.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.relobi_uncorrectable_fault.fault_count.value <= 32'h0;
        end else begin
            if(field_combo.relobi_uncorrectable_fault.fault_count.load_next) begin
                field_storage.relobi_uncorrectable_fault.fault_count.value <= field_combo.relobi_uncorrectable_fault.fault_count.next;
            end
        end
    end
    // Field: fault_monitor.core_ctrl_correctable_fault.fault_count
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.core_ctrl_correctable_fault.fault_count.value;
        load_next_c = '0;
        if(decoded_reg_strb.core_ctrl_correctable_fault && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.core_ctrl_correctable_fault.fault_count.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        if(hwif_in.core_ctrl_correctable_fault.fault_count.incr) begin // increment
            field_combo.core_ctrl_correctable_fault.fault_count.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
            next_c = next_c + 32'h1;
            load_next_c = '1;
        end else begin
            field_combo.core_ctrl_correctable_fault.fault_count.overflow = '0;
        end
        field_combo.core_ctrl_correctable_fault.fault_count.incrthreshold = (field_storage.core_ctrl_correctable_fault.fault_count.value >= 32'hffffffff);
        field_combo.core_ctrl_correctable_fault.fault_count.next = next_c;
        field_combo.core_ctrl_correctable_fault.fault_count.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.core_ctrl_correctable_fault.fault_count.value <= 32'h0;
        end else begin
            if(field_combo.core_ctrl_correctable_fault.fault_count.load_next) begin
                field_storage.core_ctrl_correctable_fault.fault_count.value <= field_combo.core_ctrl_correctable_fault.fault_count.next;
            end
        end
    end
    // Field: fault_monitor.core_ctrl_uncorrectable_fault.fault_count
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.core_ctrl_uncorrectable_fault.fault_count.value;
        load_next_c = '0;
        if(decoded_reg_strb.core_ctrl_uncorrectable_fault && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.core_ctrl_uncorrectable_fault.fault_count.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        if(hwif_in.core_ctrl_uncorrectable_fault.fault_count.incr) begin // increment
            field_combo.core_ctrl_uncorrectable_fault.fault_count.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
            next_c = next_c + 32'h1;
            load_next_c = '1;
        end else begin
            field_combo.core_ctrl_uncorrectable_fault.fault_count.overflow = '0;
        end
        field_combo.core_ctrl_uncorrectable_fault.fault_count.incrthreshold = (field_storage.core_ctrl_uncorrectable_fault.fault_count.value >= 32'hffffffff);
        field_combo.core_ctrl_uncorrectable_fault.fault_count.next = next_c;
        field_combo.core_ctrl_uncorrectable_fault.fault_count.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.core_ctrl_uncorrectable_fault.fault_count.value <= 32'h0;
        end else begin
            if(field_combo.core_ctrl_uncorrectable_fault.fault_count.load_next) begin
                field_storage.core_ctrl_uncorrectable_fault.fault_count.value <= field_combo.core_ctrl_uncorrectable_fault.fault_count.next;
            end
        end
    end
    // Field: fault_monitor.uart_fault.fault_count
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.uart_fault.fault_count.value;
        load_next_c = '0;
        if(decoded_reg_strb.uart_fault && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.uart_fault.fault_count.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        if(hwif_in.uart_fault.fault_count.incr) begin // increment
            field_combo.uart_fault.fault_count.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
            next_c = next_c + 32'h1;
            load_next_c = '1;
        end else begin
            field_combo.uart_fault.fault_count.overflow = '0;
        end
        field_combo.uart_fault.fault_count.incrthreshold = (field_storage.uart_fault.fault_count.value >= 32'hffffffff);
        field_combo.uart_fault.fault_count.next = next_c;
        field_combo.uart_fault.fault_count.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.uart_fault.fault_count.value <= 32'h0;
        end else begin
            if(field_combo.uart_fault.fault_count.load_next) begin
                field_storage.uart_fault.fault_count.value <= field_combo.uart_fault.fault_count.next;
            end
        end
    end
    // Field: fault_monitor.gpio_fault.fault_count
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.gpio_fault.fault_count.value;
        load_next_c = '0;
        if(decoded_reg_strb.gpio_fault && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.gpio_fault.fault_count.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        if(hwif_in.gpio_fault.fault_count.incr) begin // increment
            field_combo.gpio_fault.fault_count.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
            next_c = next_c + 32'h1;
            load_next_c = '1;
        end else begin
            field_combo.gpio_fault.fault_count.overflow = '0;
        end
        field_combo.gpio_fault.fault_count.incrthreshold = (field_storage.gpio_fault.fault_count.value >= 32'hffffffff);
        field_combo.gpio_fault.fault_count.next = next_c;
        field_combo.gpio_fault.fault_count.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.gpio_fault.fault_count.value <= 32'h0;
        end else begin
            if(field_combo.gpio_fault.fault_count.load_next) begin
                field_storage.gpio_fault.fault_count.value <= field_combo.gpio_fault.fault_count.next;
            end
        end
    end
    // Field: fault_monitor.timer_fault.fault_count
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.timer_fault.fault_count.value;
        load_next_c = '0;
        if(decoded_reg_strb.timer_fault && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.timer_fault.fault_count.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        if(hwif_in.timer_fault.fault_count.incr) begin // increment
            field_combo.timer_fault.fault_count.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
            next_c = next_c + 32'h1;
            load_next_c = '1;
        end else begin
            field_combo.timer_fault.fault_count.overflow = '0;
        end
        field_combo.timer_fault.fault_count.incrthreshold = (field_storage.timer_fault.fault_count.value >= 32'hffffffff);
        field_combo.timer_fault.fault_count.next = next_c;
        field_combo.timer_fault.fault_count.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.timer_fault.fault_count.value <= 32'h0;
        end else begin
            if(field_combo.timer_fault.fault_count.load_next) begin
                field_storage.timer_fault.fault_count.value <= field_combo.timer_fault.fault_count.next;
            end
        end
    end
    for(genvar i0=0; i0<2; i0++) begin
        // Field: fault_monitor.sram_scrub_correctable[].fault_count
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.sram_scrub_correctable[i0].fault_count.value;
            load_next_c = '0;
            if(decoded_reg_strb.sram_scrub_correctable[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.sram_scrub_correctable[i0].fault_count.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            if(hwif_in.sram_scrub_correctable[i0].fault_count.incr) begin // increment
                field_combo.sram_scrub_correctable[i0].fault_count.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
                next_c = next_c + 32'h1;
                load_next_c = '1;
            end else begin
                field_combo.sram_scrub_correctable[i0].fault_count.overflow = '0;
            end
            field_combo.sram_scrub_correctable[i0].fault_count.incrthreshold = (field_storage.sram_scrub_correctable[i0].fault_count.value >= 32'hffffffff);
            field_combo.sram_scrub_correctable[i0].fault_count.next = next_c;
            field_combo.sram_scrub_correctable[i0].fault_count.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.sram_scrub_correctable[i0].fault_count.value <= 32'h0;
            end else begin
                if(field_combo.sram_scrub_correctable[i0].fault_count.load_next) begin
                    field_storage.sram_scrub_correctable[i0].fault_count.value <= field_combo.sram_scrub_correctable[i0].fault_count.next;
                end
            end
        end
    end
    for(genvar i0=0; i0<2; i0++) begin
        // Field: fault_monitor.sram_scrub_uncorrectable[].fault_count
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.sram_scrub_uncorrectable[i0].fault_count.value;
            load_next_c = '0;
            if(decoded_reg_strb.sram_scrub_uncorrectable[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.sram_scrub_uncorrectable[i0].fault_count.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            if(hwif_in.sram_scrub_uncorrectable[i0].fault_count.incr) begin // increment
                field_combo.sram_scrub_uncorrectable[i0].fault_count.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
                next_c = next_c + 32'h1;
                load_next_c = '1;
            end else begin
                field_combo.sram_scrub_uncorrectable[i0].fault_count.overflow = '0;
            end
            field_combo.sram_scrub_uncorrectable[i0].fault_count.incrthreshold = (field_storage.sram_scrub_uncorrectable[i0].fault_count.value >= 32'hffffffff);
            field_combo.sram_scrub_uncorrectable[i0].fault_count.next = next_c;
            field_combo.sram_scrub_uncorrectable[i0].fault_count.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.sram_scrub_uncorrectable[i0].fault_count.value <= 32'h0;
            end else begin
                if(field_combo.sram_scrub_uncorrectable[i0].fault_count.load_next) begin
                    field_storage.sram_scrub_uncorrectable[i0].fault_count.value <= field_combo.sram_scrub_uncorrectable[i0].fault_count.next;
                end
            end
        end
    end
    for(genvar i0=0; i0<2; i0++) begin
        // Field: fault_monitor.sram_correctable_fault[].fault_count
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.sram_correctable_fault[i0].fault_count.value;
            load_next_c = '0;
            if(decoded_reg_strb.sram_correctable_fault[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.sram_correctable_fault[i0].fault_count.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            if(hwif_in.sram_correctable_fault[i0].fault_count.incr) begin // increment
                field_combo.sram_correctable_fault[i0].fault_count.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
                next_c = next_c + 32'h1;
                load_next_c = '1;
            end else begin
                field_combo.sram_correctable_fault[i0].fault_count.overflow = '0;
            end
            field_combo.sram_correctable_fault[i0].fault_count.incrthreshold = (field_storage.sram_correctable_fault[i0].fault_count.value >= 32'hffffffff);
            field_combo.sram_correctable_fault[i0].fault_count.next = next_c;
            field_combo.sram_correctable_fault[i0].fault_count.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.sram_correctable_fault[i0].fault_count.value <= 32'h0;
            end else begin
                if(field_combo.sram_correctable_fault[i0].fault_count.load_next) begin
                    field_storage.sram_correctable_fault[i0].fault_count.value <= field_combo.sram_correctable_fault[i0].fault_count.next;
                end
            end
        end
    end
    for(genvar i0=0; i0<2; i0++) begin
        // Field: fault_monitor.sram_uncorrectable_fault[].fault_count
        always_comb begin
            automatic logic [31:0] next_c;
            automatic logic load_next_c;
            next_c = field_storage.sram_uncorrectable_fault[i0].fault_count.value;
            load_next_c = '0;
            if(decoded_reg_strb.sram_uncorrectable_fault[i0] && decoded_req_is_wr) begin // SW write
                next_c = (field_storage.sram_uncorrectable_fault[i0].fault_count.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
                load_next_c = '1;
            end
            if(hwif_in.sram_uncorrectable_fault[i0].fault_count.incr) begin // increment
                field_combo.sram_uncorrectable_fault[i0].fault_count.overflow = (((33)'(next_c) + 32'h1) > 32'hffffffff);
                next_c = next_c + 32'h1;
                load_next_c = '1;
            end else begin
                field_combo.sram_uncorrectable_fault[i0].fault_count.overflow = '0;
            end
            field_combo.sram_uncorrectable_fault[i0].fault_count.incrthreshold = (field_storage.sram_uncorrectable_fault[i0].fault_count.value >= 32'hffffffff);
            field_combo.sram_uncorrectable_fault[i0].fault_count.next = next_c;
            field_combo.sram_uncorrectable_fault[i0].fault_count.load_next = load_next_c;
        end
        always_ff @(posedge clk or negedge arst_n) begin
            if(~arst_n) begin
                field_storage.sram_uncorrectable_fault[i0].fault_count.value <= 32'h0;
            end else begin
                if(field_combo.sram_uncorrectable_fault[i0].fault_count.load_next) begin
                    field_storage.sram_uncorrectable_fault[i0].fault_count.value <= field_combo.sram_uncorrectable_fault[i0].fault_count.next;
                end
            end
        end
    end

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[15];
    assign readback_array[0][31:0] = (decoded_reg_strb.relobi_correctable_fault && !decoded_req_is_wr) ? field_storage.relobi_correctable_fault.fault_count.value : '0;
    assign readback_array[1][31:0] = (decoded_reg_strb.relobi_uncorrectable_fault && !decoded_req_is_wr) ? field_storage.relobi_uncorrectable_fault.fault_count.value : '0;
    assign readback_array[2][31:0] = (decoded_reg_strb.core_ctrl_correctable_fault && !decoded_req_is_wr) ? field_storage.core_ctrl_correctable_fault.fault_count.value : '0;
    assign readback_array[3][31:0] = (decoded_reg_strb.core_ctrl_uncorrectable_fault && !decoded_req_is_wr) ? field_storage.core_ctrl_uncorrectable_fault.fault_count.value : '0;
    assign readback_array[4][31:0] = (decoded_reg_strb.uart_fault && !decoded_req_is_wr) ? field_storage.uart_fault.fault_count.value : '0;
    assign readback_array[5][31:0] = (decoded_reg_strb.gpio_fault && !decoded_req_is_wr) ? field_storage.gpio_fault.fault_count.value : '0;
    assign readback_array[6][31:0] = (decoded_reg_strb.timer_fault && !decoded_req_is_wr) ? field_storage.timer_fault.fault_count.value : '0;
    for(genvar i0=0; i0<2; i0++) begin
        assign readback_array[i0 * 1 + 7][31:0] = (decoded_reg_strb.sram_scrub_correctable[i0] && !decoded_req_is_wr) ? field_storage.sram_scrub_correctable[i0].fault_count.value : '0;
    end
    for(genvar i0=0; i0<2; i0++) begin
        assign readback_array[i0 * 1 + 9][31:0] = (decoded_reg_strb.sram_scrub_uncorrectable[i0] && !decoded_req_is_wr) ? field_storage.sram_scrub_uncorrectable[i0].fault_count.value : '0;
    end
    for(genvar i0=0; i0<2; i0++) begin
        assign readback_array[i0 * 1 + 11][31:0] = (decoded_reg_strb.sram_correctable_fault[i0] && !decoded_req_is_wr) ? field_storage.sram_correctable_fault[i0].fault_count.value : '0;
    end
    for(genvar i0=0; i0<2; i0++) begin
        assign readback_array[i0 * 1 + 13][31:0] = (decoded_reg_strb.sram_uncorrectable_fault[i0] && !decoded_req_is_wr) ? field_storage.sram_uncorrectable_fault[i0].fault_count.value : '0;
    end

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<15; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
