// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package fault_monitor_reg_pkg;

    localparam FAULT_MONITOR_REG_TOP_DATA_WIDTH = 32;
    localparam FAULT_MONITOR_REG_TOP_MIN_ADDR_WIDTH = 6;
    localparam FAULT_MONITOR_REG_TOP_SIZE = 'h3c;
    localparam NumSramBanks = 'h2;

    typedef struct {
        logic incr;
    } fault_monitor__fault_counter__fault_count__in_t;

    typedef struct {
        fault_monitor__fault_counter__fault_count__in_t fault_count;
    } fault_monitor__fault_counter__in_t;

    typedef struct {
        fault_monitor__fault_counter__in_t relobi_correctable_fault;
        fault_monitor__fault_counter__in_t relobi_uncorrectable_fault;
        fault_monitor__fault_counter__in_t core_ctrl_correctable_fault;
        fault_monitor__fault_counter__in_t core_ctrl_uncorrectable_fault;
        fault_monitor__fault_counter__in_t uart_fault;
        fault_monitor__fault_counter__in_t gpio_fault;
        fault_monitor__fault_counter__in_t timer_fault;
        fault_monitor__fault_counter__in_t sram_scrub_correctable[2];
        fault_monitor__fault_counter__in_t sram_scrub_uncorrectable[2];
        fault_monitor__fault_counter__in_t sram_correctable_fault[2];
        fault_monitor__fault_counter__in_t sram_uncorrectable_fault[2];
    } fault_monitor__in_t;
endpackage
