// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package soc_ctrl_reg_pkg;

    localparam SOC_CTRL_REG_TOP_DATA_WIDTH = 32;
    localparam SOC_CTRL_REG_TOP_MIN_ADDR_WIDTH = 5;
    localparam SOC_CTRL_REG_TOP_SIZE = 'h14;

    

    typedef struct {
        logic next;
        logic we;
    } soc_ctrl__fetchen__fetchen__in_t;

    typedef struct {
        soc_ctrl__fetchen__fetchen__in_t fetchen;
    } soc_ctrl__fetchen__in_t;

    typedef struct {
        logic next;
        logic we;
    } soc_ctrl__bootmode__bootmode__in_t;

    typedef struct {
        soc_ctrl__bootmode__bootmode__in_t bootmode;
    } soc_ctrl__bootmode__in_t;

    typedef struct {
        soc_ctrl__fetchen__in_t fetchen;
        soc_ctrl__bootmode__in_t bootmode;
    } soc_ctrl__in_t;

    typedef struct {
        logic [31:0] value;
    } soc_ctrl__bootaddr__bootaddr__out_t;

    typedef struct {
        soc_ctrl__bootaddr__bootaddr__out_t bootaddr;
    } soc_ctrl__bootaddr__out_t;

    typedef struct {
        logic value;
    } soc_ctrl__fetchen__fetchen__out_t;

    typedef struct {
        soc_ctrl__fetchen__fetchen__out_t fetchen;
    } soc_ctrl__fetchen__out_t;

    typedef struct {
        logic [31:0] value;
    } soc_ctrl__corestatus__corestatus__out_t;

    typedef struct {
        soc_ctrl__corestatus__corestatus__out_t corestatus;
    } soc_ctrl__corestatus__out_t;

    typedef struct {
        logic value;
    } soc_ctrl__bootmode__bootmode__out_t;

    typedef struct {
        soc_ctrl__bootmode__bootmode__out_t bootmode;
    } soc_ctrl__bootmode__out_t;

    typedef struct {
        logic value;
    } soc_ctrl__sram_dly__sram_dly__out_t;

    typedef struct {
        soc_ctrl__sram_dly__sram_dly__out_t sram_dly;
    } soc_ctrl__sram_dly__out_t;

    typedef struct {
        soc_ctrl__bootaddr__out_t bootaddr;
        soc_ctrl__fetchen__out_t fetchen;
        soc_ctrl__corestatus__out_t corestatus;
        soc_ctrl__bootmode__out_t bootmode;
        soc_ctrl__sram_dly__out_t sram_dly;
    } soc_ctrl__out_t;
endpackage
