// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module soc_ctrl_reg_top #(
    parameter bit [31:0] BootAddrDefault = 32'h10000000
) (
        input wire clk,
        input wire arst_n,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [4:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input soc_ctrl_reg_pkg::soc_ctrl__in_t hwif_in,
        output soc_ctrl_reg_pkg::soc_ctrl__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [4:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[4:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic bootaddr;
        logic fetchen;
        logic corestatus;
        logic bootmode;
        logic sram_dly;
        logic scrub_interval;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.bootaddr = cpuif_req_masked & (cpuif_addr == 5'h0);
        decoded_reg_strb.fetchen = cpuif_req_masked & (cpuif_addr == 5'h4);
        decoded_reg_strb.corestatus = cpuif_req_masked & (cpuif_addr == 5'h8);
        decoded_reg_strb.bootmode = cpuif_req_masked & (cpuif_addr == 5'hc);
        decoded_reg_strb.sram_dly = cpuif_req_masked & (cpuif_addr == 5'h10);
        decoded_reg_strb.scrub_interval = cpuif_req_masked & (cpuif_addr == 5'h14);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } bootaddr;
        } bootaddr;
        struct {
            struct {
                logic next;
                logic load_next;
            } fetchen;
        } fetchen;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } corestatus;
        } corestatus;
        struct {
            struct {
                logic next;
                logic load_next;
            } bootmode;
        } bootmode;
        struct {
            struct {
                logic next;
                logic load_next;
            } sram_dly;
        } sram_dly;
        struct {
            struct {
                logic [31:0] next;
                logic load_next;
            } scrub_interval;
        } scrub_interval;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [31:0] value;
            } bootaddr;
        } bootaddr;
        struct {
            struct {
                logic value;
            } fetchen;
        } fetchen;
        struct {
            struct {
                logic [31:0] value;
            } corestatus;
        } corestatus;
        struct {
            struct {
                logic value;
            } bootmode;
        } bootmode;
        struct {
            struct {
                logic value;
            } sram_dly;
        } sram_dly;
        struct {
            struct {
                logic [31:0] value;
            } scrub_interval;
        } scrub_interval;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: soc_ctrl.bootaddr.bootaddr
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bootaddr.bootaddr.value;
        load_next_c = '0;
        if(decoded_reg_strb.bootaddr && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.bootaddr.bootaddr.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.bootaddr.bootaddr.next = next_c;
        field_combo.bootaddr.bootaddr.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bootaddr.bootaddr.value <= BootAddrDefault;
        end else begin
            if(field_combo.bootaddr.bootaddr.load_next) begin
                field_storage.bootaddr.bootaddr.value <= field_combo.bootaddr.bootaddr.next;
            end
        end
    end
    assign hwif_out.bootaddr.bootaddr.value = field_storage.bootaddr.bootaddr.value;
    // Field: soc_ctrl.fetchen.fetchen
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.fetchen.fetchen.value;
        load_next_c = '0;
        if(decoded_reg_strb.fetchen && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.fetchen.fetchen.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else if(hwif_in.fetchen.fetchen.we) begin // HW Write - we
            next_c = hwif_in.fetchen.fetchen.next;
            load_next_c = '1;
        end
        field_combo.fetchen.fetchen.next = next_c;
        field_combo.fetchen.fetchen.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.fetchen.fetchen.value <= 1'h0;
        end else begin
            if(field_combo.fetchen.fetchen.load_next) begin
                field_storage.fetchen.fetchen.value <= field_combo.fetchen.fetchen.next;
            end
        end
    end
    assign hwif_out.fetchen.fetchen.value = field_storage.fetchen.fetchen.value;
    // Field: soc_ctrl.corestatus.corestatus
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.corestatus.corestatus.value;
        load_next_c = '0;
        if(decoded_reg_strb.corestatus && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.corestatus.corestatus.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.corestatus.corestatus.next = next_c;
        field_combo.corestatus.corestatus.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.corestatus.corestatus.value <= 32'h0;
        end else begin
            if(field_combo.corestatus.corestatus.load_next) begin
                field_storage.corestatus.corestatus.value <= field_combo.corestatus.corestatus.next;
            end
        end
    end
    assign hwif_out.corestatus.corestatus.value = field_storage.corestatus.corestatus.value;
    // Field: soc_ctrl.bootmode.bootmode
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.bootmode.bootmode.value;
        load_next_c = '0;
        if(decoded_reg_strb.bootmode && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.bootmode.bootmode.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else if(hwif_in.bootmode.bootmode.we) begin // HW Write - we
            next_c = hwif_in.bootmode.bootmode.next;
            load_next_c = '1;
        end
        field_combo.bootmode.bootmode.next = next_c;
        field_combo.bootmode.bootmode.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.bootmode.bootmode.value <= 1'h0;
        end else begin
            if(field_combo.bootmode.bootmode.load_next) begin
                field_storage.bootmode.bootmode.value <= field_combo.bootmode.bootmode.next;
            end
        end
    end
    assign hwif_out.bootmode.bootmode.value = field_storage.bootmode.bootmode.value;
    // Field: soc_ctrl.sram_dly.sram_dly
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.sram_dly.sram_dly.value;
        load_next_c = '0;
        if(decoded_reg_strb.sram_dly && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.sram_dly.sram_dly.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.sram_dly.sram_dly.next = next_c;
        field_combo.sram_dly.sram_dly.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.sram_dly.sram_dly.value <= 1'h1;
        end else begin
            if(field_combo.sram_dly.sram_dly.load_next) begin
                field_storage.sram_dly.sram_dly.value <= field_combo.sram_dly.sram_dly.next;
            end
        end
    end
    assign hwif_out.sram_dly.sram_dly.value = field_storage.sram_dly.sram_dly.value;
    // Field: soc_ctrl.scrub_interval.scrub_interval
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.scrub_interval.scrub_interval.value;
        load_next_c = '0;
        if(decoded_reg_strb.scrub_interval && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.scrub_interval.scrub_interval.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.scrub_interval.scrub_interval.next = next_c;
        field_combo.scrub_interval.scrub_interval.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.scrub_interval.scrub_interval.value <= 32'h0;
        end else begin
            if(field_combo.scrub_interval.scrub_interval.load_next) begin
                field_storage.scrub_interval.scrub_interval.value <= field_combo.scrub_interval.scrub_interval.next;
            end
        end
    end
    assign hwif_out.scrub_interval.scrub_interval.value = field_storage.scrub_interval.scrub_interval.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[6];
    assign readback_array[0][31:0] = (decoded_reg_strb.bootaddr && !decoded_req_is_wr) ? field_storage.bootaddr.bootaddr.value : '0;
    assign readback_array[1][0:0] = (decoded_reg_strb.fetchen && !decoded_req_is_wr) ? field_storage.fetchen.fetchen.value : '0;
    assign readback_array[1][31:1] = '0;
    assign readback_array[2][31:0] = (decoded_reg_strb.corestatus && !decoded_req_is_wr) ? field_storage.corestatus.corestatus.value : '0;
    assign readback_array[3][0:0] = (decoded_reg_strb.bootmode && !decoded_req_is_wr) ? field_storage.bootmode.bootmode.value : '0;
    assign readback_array[3][31:1] = '0;
    assign readback_array[4][0:0] = (decoded_reg_strb.sram_dly && !decoded_req_is_wr) ? field_storage.sram_dly.sram_dly.value : '0;
    assign readback_array[4][31:1] = '0;
    assign readback_array[5][31:0] = (decoded_reg_strb.scrub_interval && !decoded_req_is_wr) ? field_storage.scrub_interval.scrub_interval.value : '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<6; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
