# Copyright 2022 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51
#
# Nicole Narr <narrn@student.ethz.ch>
# Christopher Reinwardt <creinwar@student.ethz.ch>
# Cyril Koenig <cykoenig@iis.ee.ethz.ch>
# Paul Scheffler <paulsc@iis.ee.ethz.ch>

#############
# Sys Clock #
#############

# 100 MHz input clock
set SYS_TCK 10
create_clock -period $SYS_TCK -name sys_clk_p [get_ports sys_clk_p]

# SoC clock is generated by clock wizard and its constraints
set SOC_TCK 50.0
set soc_clk [get_clocks -of_objects [get_pins i_clkwiz/clk_20]]

############
# Switches #
############

set_input_delay -min -clock $soc_clk [expr { $SOC_TCK * 0.10 }] [ \
    get_ports {gpio_i*}]
set_input_delay -max -clock $soc_clk [expr { $SOC_TCK * 0.35 }] [ \
    get_ports {gpio_i*}]

set_max_delay [expr { 2 * $SOC_TCK }] -from [get_ports {gpio_i*}]
set_false_path -hold -from [get_ports {gpio_i*}]

# LEDs
set_output_delay -min -clock $soc_clk [expr { $SOC_TCK * 0.10 }] [get_ports gpio_o]
set_output_delay -max -clock $soc_clk [expr { $SOC_TCK * 0.35 }] [get_ports gpio_o]


###############
# Assign Pins #
###############

# tclint-disable line-length, spacing

## Clock Signal
set_property -dict { PACKAGE_PIN W5    IOSTANDARD LVCMOS33 } [get_ports { sys_clk_p }]; 

## Buttons
set_property -dict { PACKAGE_PIN U18   IOSTANDARD LVCMOS33 } [get_ports { sys_reset }]; # CHECKME polarity

## Switches
set_property -dict { PACKAGE_PIN V17   IOSTANDARD LVCMOS33 } [get_ports { gpio_i[0] }]; # SW0
set_property -dict { PACKAGE_PIN V16   IOSTANDARD LVCMOS33 } [get_ports { gpio_i[1] }]; # SW1
set_property -dict { PACKAGE_PIN W16   IOSTANDARD LVCMOS33 } [get_ports { gpio_i[2] }]; # SW2
set_property -dict { PACKAGE_PIN W17   IOSTANDARD LVCMOS33 } [get_ports { gpio_i[3] }]; # SW3
# set_property -dict { PACKAGE_PIN R2   IOSTANDARD LVCMOS33 } [get_ports { fetch_en_i }]; # SW15

## LEDs
set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[0] }]; # LD0
set_property -dict { PACKAGE_PIN E19   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[1] }]; # LD1
set_property -dict { PACKAGE_PIN U19   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[2] }]; # LD2
set_property -dict { PACKAGE_PIN V19   IOSTANDARD LVCMOS33 } [get_ports { gpio_o[3] }]; # LD3
set_property -dict { PACKAGE_PIN L1   IOSTANDARD LVCMOS33 } [get_ports { status_o }]; # LD15

## UART
set_property -dict { PACKAGE_PIN A18   IOSTANDARD LVCMOS33 } [get_ports { uart_tx_o }];
# set_property -dict { PACKAGE_PIN P1    IOSTANDARD LVCMOS33 } [get_ports { uart_tx_o }]; # LD14
set_property -dict { PACKAGE_PIN B18   IOSTANDARD LVCMOS33 } [get_ports { uart_rx_i }];

# tclint-enable line-length, spacing