# Copyright (c) 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Author:  Philippe Sauter <phsauter@iis.ee.ethz.ch>

name: 'OSEDA Caching'
description: 'Cache OSEDA Docker Images'

runs:
  using: 'composite'
  steps:
    - name: Get image name from docker-compose
      id: get-image
      shell: bash
      run: |
        echo "UID=$(id -u)" >> $GITHUB_ENV
        echo "GID=$(id -g)" >> $GITHUB_ENV
        IMAGE=$(docker compose config | awk '/image:/{print $2}' | head -n1)
        echo "IMAGE_NAME=$IMAGE" >> $GITHUB_ENV

    - name: Restore Docker image cache
      id: restore-cache
      uses: actions/cache@v4
      with:
        path: /tmp/oseda.tar.gz
        key: oseda-${{ env.IMAGE_NAME }}

    - name: Check disk usage
      shell: bash
      run: df -h

    - name: Load cached Docker image
      shell: bash
      if: steps.restore-cache.outputs.cache-hit == 'true'
      run: docker import /tmp/oseda.tar.gz

    - name: Prepare Docker image for caching
      shell: bash
      if: steps.restore-cache.outputs.cache-hit != 'true'
      run: |
        docker system prune -af
        docker compose pull
        df -h
        docker save $IMAGE_NAME | pigz -9 -f > /tmp/oseda.tar.gz
        df -h

    - name: Check disk usage
      shell: bash
      run: df -h
