
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
../rtl/common_verification/clk_rst_gen.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
../rtl/tech_cells_generic/tc_sram.sv
../rtl/tech_cells_generic/tc_sram_impl.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
../rtl/tech_cells_generic/tc_clk.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/common_cells/include
../rtl/common_cells/binary_to_gray.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/common_cells/include
../rtl/common_cells/cb_filter_pkg.sv
../rtl/common_cells/cc_onehot.sv
../rtl/common_cells/cdc_reset_ctrlr_pkg.sv
../rtl/common_cells/cf_math_pkg.sv
../rtl/common_cells/clk_int_div.sv
../rtl/common_cells/credit_counter.sv
../rtl/common_cells/delta_counter.sv
../rtl/common_cells/ecc_pkg.sv
../rtl/common_cells/edge_propagator_tx.sv
../rtl/common_cells/exp_backoff.sv
../rtl/common_cells/fifo_v3.sv
../rtl/common_cells/gray_to_binary.sv
../rtl/common_cells/isochronous_4phase_handshake.sv
../rtl/common_cells/isochronous_spill_register.sv
../rtl/common_cells/lfsr.sv
../rtl/common_cells/lfsr_16bit.sv
../rtl/common_cells/lfsr_8bit.sv
../rtl/common_cells/lossy_valid_to_stream.sv
../rtl/common_cells/mv_filter.sv
../rtl/common_cells/onehot_to_bin.sv
../rtl/common_cells/plru_tree.sv
../rtl/common_cells/passthrough_stream_fifo.sv
../rtl/common_cells/popcount.sv
../rtl/common_cells/rr_arb_tree.sv
../rtl/common_cells/rstgen_bypass.sv
../rtl/common_cells/serial_deglitch.sv
../rtl/common_cells/shift_reg.sv
../rtl/common_cells/shift_reg_gated.sv
../rtl/common_cells/spill_register_flushable.sv
../rtl/common_cells/stream_demux.sv
../rtl/common_cells/stream_filter.sv
../rtl/common_cells/stream_fork.sv
../rtl/common_cells/stream_intf.sv
../rtl/common_cells/stream_join_dynamic.sv
../rtl/common_cells/stream_mux.sv
../rtl/common_cells/stream_throttle.sv
../rtl/common_cells/sub_per_hash.sv
../rtl/common_cells/sync.sv
../rtl/common_cells/sync_wedge.sv
../rtl/common_cells/unread.sv
../rtl/common_cells/read.sv
../rtl/common_cells/addr_decode_dync.sv
../rtl/common_cells/cdc_2phase.sv
../rtl/common_cells/cdc_4phase.sv
../rtl/common_cells/clk_int_div_static.sv
../rtl/common_cells/addr_decode.sv
../rtl/common_cells/addr_decode_napot.sv
../rtl/common_cells/multiaddr_decode.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/common_cells/include
../rtl/common_cells/cb_filter.sv
../rtl/common_cells/cdc_fifo_2phase.sv
../rtl/common_cells/clk_mux_glitch_free.sv
../rtl/common_cells/counter.sv
../rtl/common_cells/ecc_decode.sv
../rtl/common_cells/ecc_encode.sv
../rtl/common_cells/edge_detect.sv
../rtl/common_cells/lzc.sv
../rtl/common_cells/max_counter.sv
../rtl/common_cells/rstgen.sv
../rtl/common_cells/spill_register.sv
../rtl/common_cells/stream_delay.sv
../rtl/common_cells/stream_fifo.sv
../rtl/common_cells/stream_fork_dynamic.sv
../rtl/common_cells/stream_join.sv
../rtl/common_cells/cdc_reset_ctrlr.sv
../rtl/common_cells/cdc_fifo_gray.sv
../rtl/common_cells/fall_through_register.sv
../rtl/common_cells/id_queue.sv
../rtl/common_cells/stream_to_mem.sv
../rtl/common_cells/stream_arbiter_flushable.sv
../rtl/common_cells/stream_fifo_optimal_wrap.sv
../rtl/common_cells/stream_register.sv
../rtl/common_cells/stream_xbar.sv
../rtl/common_cells/cdc_fifo_gray_clearable.sv
../rtl/common_cells/cdc_2phase_clearable.sv
../rtl/common_cells/mem_to_banks_detailed.sv
../rtl/common_cells/stream_arbiter.sv
../rtl/common_cells/stream_omega_net.sv
../rtl/common_cells/mem_to_banks.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/apb/include
+incdir+../rtl/common_cells/include
../rtl/apb/apb_pkg.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/apb/include
+incdir+../rtl/common_cells/include
+incdir+../rtl/register_interface/include
../rtl/register_interface/reg_intf.sv
../rtl/register_interface/lowrisc_opentitan/prim_subreg_arb.sv
../rtl/register_interface/lowrisc_opentitan/prim_subreg_ext.sv
../rtl/register_interface/periph_to_reg.sv
../rtl/register_interface/reg_to_apb.sv
../rtl/register_interface/lowrisc_opentitan/prim_subreg_shadow.sv
../rtl/register_interface/lowrisc_opentitan/prim_subreg.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/apb/include
+incdir+../rtl/register_interface/include
../rtl/apb_uart/slib_clock_div.sv
../rtl/apb_uart/slib_counter.sv
../rtl/apb_uart/slib_edge_detect.sv
../rtl/apb_uart/slib_fifo.sv
../rtl/apb_uart/slib_input_filter.sv
../rtl/apb_uart/slib_input_sync.sv
../rtl/apb_uart/slib_mv_filter.sv
../rtl/apb_uart/uart_baudgen.sv
../rtl/apb_uart/uart_interrupt.sv
../rtl/apb_uart/uart_receiver.sv
../rtl/apb_uart/uart_transmitter.sv
../rtl/apb_uart/apb_uart.sv
../rtl/apb_uart/apb_uart_wrap.sv
../rtl/apb_uart/reg_uart_wrap.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/cve2/include
../rtl/cve2/cve2_pkg.sv
../rtl/cve2/cve2_alu.sv
../rtl/cve2/cve2_compressed_decoder.sv
../rtl/cve2/cve2_controller.sv
../rtl/cve2/cve2_counter.sv
../rtl/cve2/cve2_csr.sv
../rtl/cve2/cve2_decoder.sv
../rtl/cve2/cve2_fetch_fifo.sv
../rtl/cve2/cve2_load_store_unit.sv
../rtl/cve2/cve2_multdiv_fast.sv
../rtl/cve2/cve2_multdiv_slow.sv
../rtl/cve2/cve2_pmp.sv
../rtl/cve2/cve2_register_file_ff.sv
../rtl/cve2/cve2_wb.sv
../rtl/cve2/cve2_cs_registers.sv
../rtl/cve2/cve2_ex_block.sv
../rtl/cve2/cve2_id_stage.sv
../rtl/cve2/cve2_prefetch_buffer.sv
../rtl/cve2/cve2_if_stage.sv
../rtl/cve2/cve2_core.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/common_cells/include
+incdir+../rtl/obi/include
../rtl/obi/obi_pkg.sv
../rtl/obi/obi_intf.sv
../rtl/obi/obi_rready_converter.sv
../rtl/obi/obi_atop_resolver.sv
../rtl/obi/obi_demux.sv
../rtl/obi/obi_err_sbr.sv
../rtl/obi/obi_mux.sv
../rtl/obi/obi_sram_shim.sv
../rtl/obi/obi_xbar.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/common_cells/include
../rtl/riscv-dbg/dm_pkg.sv
../rtl/riscv-dbg/debug_rom/debug_rom.sv
../rtl/riscv-dbg/debug_rom/debug_rom_one_scratch.sv
../rtl/riscv-dbg/dm_csrs.sv
../rtl/riscv-dbg/dm_mem.sv
../rtl/riscv-dbg/dmi_cdc.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/common_cells/include
../rtl/riscv-dbg/dmi_jtag_tap.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/common_cells/include
../rtl/riscv-dbg/dm_sba.sv
../rtl/riscv-dbg/dm_top.sv
../rtl/riscv-dbg/dmi_jtag.sv
../rtl/riscv-dbg/dm_obi_top.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/common_cells/include
../rtl/riscv-dbg/tb/jtag_test_simple.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
../rtl/timer_unit/timer_unit_counter.sv
../rtl/timer_unit/timer_unit_counter_presc.sv
../rtl/timer_unit/apb_timer_unit.sv
../rtl/timer_unit/timer_unit.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/apb/include
+incdir+../rtl/common_cells/include
+incdir+../rtl/obi/include
+incdir+../rtl/register_interface/include
../rtl/croc_pkg.sv
../rtl/user_pkg.sv
../rtl/soc_ctrl/soc_ctrl_reg_pkg.sv
../rtl/gpio/gpio_reg_pkg.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/apb/include
+incdir+../rtl/common_cells/include
+incdir+../rtl/obi/include
+incdir+../rtl/register_interface/include
../rtl/core_wrap.sv
../rtl/soc_ctrl/soc_ctrl_reg_top.sv
../rtl/gpio/gpio_reg_top.sv
../rtl/gpio/gpio.sv
../rtl/croc_domain.sv
../rtl/user_domain.sv
../rtl/croc_soc.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/apb/include
+incdir+../rtl/common_cells/include
+incdir+../rtl/obi/include
+incdir+../rtl/register_interface/include
../rtl/croc_chip.sv

+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+SYNTHESIS
+define+VERILATOR
+incdir+../rtl/apb/include
+incdir+../rtl/common_cells/include
+incdir+../rtl/obi/include
+incdir+../rtl/register_interface/include
../rtl/tb_croc_soc.sv

