/* Generated by Yosys 0.35 (git sha1 cc31c6ebc45, gcc-11.2.0 11.2.0 -fPIC -Os) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "../pickle/croc_sv2v.v:1.1-55.10" *)
module delta_counter__2820661119834649917(clk_i, rst_ni, clear_i, en_i, load_i, down_i, delta_i, d_i, q_o, overflow_o);
  reg \$auto$verilog_backend.cc:2189:dump_module$4319  = 0;
  (* src = "../pickle/croc_sv2v.v:0.0-0.0" *)
  reg \$0\_sv2v_0[0:0] ;
  (* src = "../pickle/croc_sv2v.v:34.2-48.5" *)
  reg [1:0] \$0\counter_d[1:0] ;
  (* src = "../pickle/croc_sv2v.v:49.2-53.27" *)
  reg [1:0] \$0\counter_q[1:0] ;
  (* src = "../pickle/croc_sv2v.v:34.2-48.5" *)
  reg [1:0] \$1\counter_d[1:0] ;
  (* src = "../pickle/croc_sv2v.v:34.2-48.5" *)
  reg [1:0] \$2\counter_d[1:0] ;
  (* src = "../pickle/croc_sv2v.v:34.2-48.5" *)
  reg [1:0] \$3\counter_d[1:0] ;
  (* src = "../pickle/croc_sv2v.v:34.2-48.5" *)
  reg [1:0] \$4\counter_d[1:0] ;
  (* src = "../pickle/croc_sv2v.v:46.17-46.36" *)
  wire [1:0] \$add$../pickle/croc_sv2v.v:46$24_Y ;
  (* src = "../pickle/croc_sv2v.v:50.7-50.14" *)
  wire \$logic_not$../pickle/croc_sv2v.v:50$26_Y ;
  (* src = "../pickle/croc_sv2v.v:44.17-44.36" *)
  wire [1:0] \$sub$../pickle/croc_sv2v.v:44$23_Y ;
  (* src = "../pickle/croc_sv2v.v:13.6-13.13" *)
  reg _sv2v_0;
  (* src = "../pickle/croc_sv2v.v:18.13-18.20" *)
  input clear_i;
  wire clear_i;
  (* src = "../pickle/croc_sv2v.v:16.13-16.18" *)
  input clk_i;
  wire clk_i;
  (* src = "../pickle/croc_sv2v.v:27.16-27.25" *)
  reg [1:0] counter_d;
  (* src = "../pickle/croc_sv2v.v:26.16-26.25" *)
  reg [1:0] counter_q;
  (* src = "../pickle/croc_sv2v.v:23.27-23.30" *)
  input d_i;
  wire d_i;
  (* src = "../pickle/croc_sv2v.v:22.27-22.34" *)
  input delta_i;
  wire delta_i;
  (* src = "../pickle/croc_sv2v.v:21.13-21.19" *)
  input down_i;
  wire down_i;
  (* src = "../pickle/croc_sv2v.v:19.13-19.17" *)
  input en_i;
  wire en_i;
  (* src = "../pickle/croc_sv2v.v:20.13-20.19" *)
  input load_i;
  wire load_i;
  (* src = "../pickle/croc_sv2v.v:25.14-25.24" *)
  output overflow_o;
  wire overflow_o;
  (* src = "../pickle/croc_sv2v.v:24.28-24.31" *)
  output q_o;
  wire q_o;
  (* src = "../pickle/croc_sv2v.v:17.13-17.19" *)
  input rst_ni;
  wire rst_ni;
  (* src = "../pickle/croc_sv2v.v:46.17-46.36" *)
  \$add  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd2)
  ) \$add$../pickle/croc_sv2v.v:46$24  (
    .A(counter_q),
    .B(delta_i),
    .Y(\$add$../pickle/croc_sv2v.v:46$24_Y )
  );
  (* src = "../pickle/croc_sv2v.v:50.7-50.14" *)
  \$logic_not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) \$logic_not$../pickle/croc_sv2v.v:50$26  (
    .A(rst_ni),
    .Y(\$logic_not$../pickle/croc_sv2v.v:50$26_Y )
  );
  (* src = "../pickle/croc_sv2v.v:44.17-44.36" *)
  \$sub  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd2),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd2)
  ) \$sub$../pickle/croc_sv2v.v:44$23  (
    .A(counter_q),
    .B(delta_i),
    .Y(\$sub$../pickle/croc_sv2v.v:44$23_Y )
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$4319 ) begin end
    \$0\_sv2v_0[0:0]  = 1'h0;
  end
  always @* begin
      _sv2v_0 <= \$0\_sv2v_0[0:0] ;
  end
  initial begin
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$4319 ) begin end
    \$0\counter_d[1:0]  = \$1\counter_d[1:0] ;
    (* src = "../pickle/croc_sv2v.v:35.3-36.5" *)
    casez (_sv2v_0)
      /* src = "../pickle/croc_sv2v.v:35.7-35.14" */
      1'h1:
          /* empty */;
      default:
          /* empty */;
    endcase
    (* src = "../pickle/croc_sv2v.v:38.3-47.6" *)
    casez (clear_i)
      /* src = "../pickle/croc_sv2v.v:38.7-38.14" */
      1'h1:
          \$1\counter_d[1:0]  = 2'h0;
      /* src = "../pickle/croc_sv2v.v:40.3-40.7" */
      default:
        begin
          \$1\counter_d[1:0]  = \$2\counter_d[1:0] ;
          (* src = "../pickle/croc_sv2v.v:40.8-47.6" *)
          casez (load_i)
            /* src = "../pickle/croc_sv2v.v:40.12-40.18" */
            1'h1:
                \$2\counter_d[1:0]  = { 1'h0, d_i };
            /* src = "../pickle/croc_sv2v.v:42.3-42.7" */
            default:
              begin
                \$2\counter_d[1:0]  = \$3\counter_d[1:0] ;
                (* src = "../pickle/croc_sv2v.v:42.8-47.6" *)
                casez (en_i)
                  /* src = "../pickle/croc_sv2v.v:42.12-42.16" */
                  1'h1:
                    begin
                      \$3\counter_d[1:0]  = \$4\counter_d[1:0] ;
                      (* src = "../pickle/croc_sv2v.v:43.4-46.37" *)
                      casez (down_i)
                        /* src = "../pickle/croc_sv2v.v:43.8-43.14" */
                        1'h1:
                            \$4\counter_d[1:0]  = \$sub$../pickle/croc_sv2v.v:44$23_Y ;
                        /* src = "../pickle/croc_sv2v.v:45.4-45.8" */
                        default:
                            \$4\counter_d[1:0]  = \$add$../pickle/croc_sv2v.v:46$24_Y ;
                      endcase
                    end
                  default:
                      \$3\counter_d[1:0]  = counter_q;
                endcase
              end
          endcase
        end
    endcase
  end
  always @* begin
      counter_d <= \$0\counter_d[1:0] ;
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2189:dump_module$4319 ) begin end
    \$0\counter_q[1:0]  = counter_q;
    (* src = "../pickle/croc_sv2v.v:50.3-53.27" *)
    casez (\$logic_not$../pickle/croc_sv2v.v:50$26_Y )
      /* src = "../pickle/croc_sv2v.v:50.7-50.14" */
      1'h1:
          \$0\counter_q[1:0]  = 2'h0;
      /* src = "../pickle/croc_sv2v.v:52.3-52.7" */
      default:
          \$0\counter_q[1:0]  = counter_d;
    endcase
  end
  always @(posedge clk_i) begin
      counter_q <= \$0\counter_q[1:0] ;
  end
  always @(negedge rst_ni) begin
      counter_q <= \$0\counter_q[1:0] ;
  end
  assign q_o = counter_q[0];
  assign overflow_o = counter_q[1];
endmodule
